// Generated by design/tools/sources/generate.py -- do not edit by hand.
// Source of truth: design/tokens.xml + design/themes.xml
// Regenerate with: npm run design:gen
import { vars } from 'nativewind';

// Raw color values (space-separated RGB) - edit design/themes.xml and regenerate
export const colors = {
  light: {
    '--background': '250 250 250',
    '--foreground': '24 24 27',
    '--card': '255 255 255',
    '--card-foreground': '24 24 27',
    '--popover': '255 255 255',
    '--popover-foreground': '24 24 27',
    '--primary': '37 99 235',
    '--primary-foreground': '255 255 255',
    '--secondary': '71 85 105',
    '--secondary-foreground': '255 255 255',
    '--muted': '244 244 245',
    '--muted-foreground': '82 82 91',
    '--accent': '239 246 255',
    '--accent-foreground': '30 58 138',
    '--destructive': '220 38 38',
    '--destructive-foreground': '255 255 255',
    '--border': '228 228 231',
    '--input': '228 228 231',
    '--ring': '59 130 246',
    '--success': '22 163 74',
    '--success-foreground': '255 255 255',
    '--warning': '217 119 6',
    '--warning-foreground': '255 255 255',
    '--error': '220 38 38',
    '--error-foreground': '255 255 255',
    '--info': '2 132 199',
    '--info-foreground': '255 255 255',
  },
  dark: {
    '--background': '24 24 27',
    '--foreground': '244 244 245',
    '--card': '39 39 42',
    '--card-foreground': '244 244 245',
    '--popover': '39 39 42',
    '--popover-foreground': '244 244 245',
    '--primary': '59 130 246',
    '--primary-foreground': '255 255 255',
    '--secondary': '100 116 139',
    '--secondary-foreground': '255 255 255',
    '--muted': '39 39 42',
    '--muted-foreground': '161 161 170',
    '--accent': '30 58 138',
    '--accent-foreground': '219 234 254',
    '--destructive': '239 68 68',
    '--destructive-foreground': '255 255 255',
    '--border': '63 63 70',
    '--input': '63 63 70',
    '--ring': '96 165 250',
    '--success': '34 197 94',
    '--success-foreground': '24 24 27',
    '--warning': '245 158 11',
    '--warning-foreground': '24 24 27',
    '--error': '239 68 68',
    '--error-foreground': '255 255 255',
    '--info': '14 165 233',
    '--info-foreground': '255 255 255',
  },
};

// Config for nativewind vars() - used by the provider
export const config = {
  light: vars(colors.light),
  dark: vars(colors.dark),
};
