"""Shared imports, namespace and helpers for the .generate package.

This package has exactly one responsibility: turn the design registries
(design/tokens.xml + design/themes.xml) into the gluestack-ui/nativewind theme
configuration consumed by components/ui/gluestack-ui-provider/config.ts.

The sibling modules (config.py, model.py, cli.py) rely on
`from .common import *` to see these names, so the "unused" imports below are
deliberate re-exports (hence the noqa: F401 markers).
"""

from __future__ import annotations

import argparse  # noqa: F401  (re-exported via `from .common import *`)
import re  # noqa: F401  (re-exported via `from .common import *`)
import sys
from dataclasses import (  # noqa: F401  (re-exported via `from .common import *`)
    dataclass,
    field,
)
from pathlib import Path

from lxml import etree  # noqa: F401  (re-exported via `from .common import *`)

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import checker  # noqa: F401  (registry model; re-exported via `from .common import *`)

NS = "urn:flipova:foundation:registry"
GENERATOR_NOTE = "generated by design/tools/sources/generate.py -- do not edit by hand"


def q(tag: str) -> str:
    return f"{{{NS}}}{tag}"
