"""gluestack / nativewind config emitter.

Compiles design/tokens.xml + design/themes.xml into
components/ui/gluestack-ui-provider/config.ts:

  - each theme (themes.xml) becomes a `colors.<theme-id>` record;
  - each role id (the gluestack CSS variable name without the leading "--")
    becomes a `'--<role>'` entry;
  - each role value is resolved against the tokens registry and normalised to a
    space-separated RGB triplet (the nativewind/gluestack colour format).
"""

from __future__ import annotations

from .common import *
from .model import ManifestModel

_HEADER = [
    "// Generated by design/tools/sources/generate.py -- do not edit by hand.",
    "// Source of truth: design/tokens.xml + design/themes.xml",
    "// Regenerate with: npm run design:gen",
    "import { vars } from 'nativewind';",
    "",
]


def _to_rgb_triplet(literal: str) -> str:
    """Normalise a resolved colour to the gluestack format ('r g b')."""
    text = literal.strip()
    if text.startswith("#"):
        digits = text[1:]
        if len(digits) == 3:
            digits = "".join(ch * 2 for ch in digits)
        if len(digits) != 6:
            raise SystemExit(f"unsupported colour {literal!r} (expected #RGB or #RRGGBB)")
        r, g, b = (int(digits[i:i + 2], 16) for i in (0, 2, 4))
        return f"{r} {g} {b}"
    # Already a literal gluestack value (space-separated RGB triplet).
    return " ".join(text.split())


def _resolve_colour(ctx: checker.RegistryModel, ref: str) -> str:
    """Resolve `$ref.<register>.<id>.<path>` against the tokens registry."""
    raw = ref.strip()
    parts = raw[len("$ref."):].split(".") if raw.startswith("$ref.") else raw.split(".")
    if parts and parts[0] in ctx.registers:
        parts = parts[1:]
    if len(parts) < 2:
        raise SystemExit(f"dangling reference {ref!r} (expected $ref.<register>.<id>.<path>)")
    item_id, key = parts[0], ".".join(parts[1:])
    values = ctx.token_values.get(item_id)
    if values is None or key not in values:
        raise SystemExit(f"dangling reference {ref!r}: no token value matches")
    return values[key]


def theme_role_colours(man: ManifestModel) -> list[tuple[str, list[tuple[str, str]]]]:
    """[(theme_id, [(role_id, 'r g b'), ...]), ...] in themes.xml order."""
    themes_path = man.ctx.catalog_files.get("themes")
    if themes_path is None or not themes_path.exists():
        raise SystemExit("manifest: no themes catalog file found")
    root = etree.parse(str(themes_path)).getroot()
    themes: list[tuple[str, list[tuple[str, str]]]] = []
    for theme in root.findall(q("items") + "/" + q("theme")):
        tid = (theme.get("id") or "").strip()
        roles: list[tuple[str, str]] = []
        for role in theme.findall(q("roleMap") + "/" + q("role")):
            rid = (role.get("id") or "").strip()
            ref_el = role.find(q("ref"))
            val_el = role.find(q("value"))
            if ref_el is not None:
                literal = _resolve_colour(man.ctx, ref_el.text or "")
            elif val_el is not None:
                literal = val_el.text or ""
            else:
                raise SystemExit(f"theme {tid!r}: role {rid!r} needs a <ref> or a <value>")
            roles.append((rid, _to_rgb_triplet(literal)))
        themes.append((tid, roles))
    return themes


def theme_role_ids(man: ManifestModel) -> list[str]:
    """Ordered semantic role ids (the gluestack CSS variable names), from themes.xml.

    A role id defines the semantic colour surface of the design system, so it is
    emitted twice: as a `'--<role>'` variable in config.ts, and as a
    `rgb(var(--<role>)/<alpha-value>)` colour in the Tailwind theme (tokens.js).
    Every theme must therefore declare the same roles.
    """
    themes = theme_role_colours(man)
    if not themes:
        return []
    reference = [rid for rid, _ in themes[0][1]]
    for tid, roles in themes[1:]:
        others = [rid for rid, _ in roles]
        if others != reference:
            print(f"warning: theme {tid!r} declares a different role set than "
                  f"{themes[0][0]!r} (Tailwind colours are generated from {themes[0][0]!r})")
    return reference


_JS_IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _js_key(name: str) -> str:
    """Quote an object key unless it is a bare JS identifier.

    A theme id is free-form ("spring-light", "high-contrast"), but `spring-light`
    is not a valid unquoted object key: emitting it bare produces a syntax error.
    """
    return name if _JS_IDENT.match(name) else "'" + name.replace("'", "\\'") + "'"


def theme_variants(man: ManifestModel) -> list[tuple[str, str, str]]:
    """[(variant, mode, theme_id), ...] in themes.xml order.

    A variant is a light/dark PAIR, so the runtime can resolve a (variant, mode)
    request to a theme id. The table is emitted rather than rebuilt at runtime so
    a theme id never has to follow a naming convention: a variant may be spelled
    `spring` with themes `spring-light`/`spring-dark`, or anything else at all.
    """
    themes_path = man.ctx.catalog_files.get("themes")
    if themes_path is None or not themes_path.exists():
        raise SystemExit("manifest: no themes catalog file found")
    root = etree.parse(str(themes_path)).getroot()
    out: list[tuple[str, str, str]] = []
    for theme in root.findall(q("items") + "/" + q("theme")):
        tid = (theme.get("id") or "").strip()
        mode = (theme.get("mode") or "").strip()
        variant = (theme.get("variant") or "default").strip() or "default"
        out.append((variant, mode, tid))
    return out


def _render_variant_table(variants: list[tuple[str, str, str]]) -> list[str]:
    """`export const variants = { spring: { light: 'spring-light', ... } }`."""
    ordered: dict[str, list[tuple[str, str]]] = {}
    for variant, mode, tid in variants:
        entries = ordered.setdefault(variant, [])
        if any(m == mode for m, _ in entries):
            raise SystemExit(
                f"theme variant {variant!r} declares the mode {mode!r} twice: "
                "a variant is a light/dark pair, so it has exactly one theme per mode"
            )
        entries.append((mode, tid))
    lines = ["export const variants = {"]
    for variant in sorted(ordered):
        pairs = ", ".join(f"{_js_key(mode)}: '{tid}'" for mode, tid in sorted(ordered[variant]))
        lines.append(f"  {_js_key(variant)}: {{ {pairs} }},")
    lines.append("};")
    return lines


def render_gluestack_config(man: ManifestModel) -> str:
    themes = theme_role_colours(man)
    lines = list(_HEADER)
    lines.append("// Raw color values (space-separated RGB) - edit design/themes.xml and regenerate")
    lines.append("export const colors = {")
    for tid, roles in themes:
        lines.append(f"  {_js_key(tid)}: {{")
        for rid, triplet in roles:
            lines.append(f"    '--{rid}': '{triplet}',")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("// Config for nativewind vars() - used by the provider")
    lines.append("export const config = {")
    for tid, _ in themes:
        # Bracket access, always: a quoted key ("spring-light") is not valid
        # after a dot, so `colors.something` would only work by luck.
        lines.append(f"  {_js_key(tid)}: vars(colors['{tid}']),")
    lines.append("};")
    lines.append("")
    lines.append("// Theme variants: variant -> mode -> theme id, from the `variant` attribute in")
    lines.append("// design/themes.xml. `default` holds the base light/dark pair.")
    lines.extend(_render_variant_table(theme_variants(man)))
    return "\n".join(lines) + "\n"
