"""Tailwind / nativewind token emitter (design/tokens.xml + themes.xml -> tokens.js).

Turns the registries into the whole Tailwind `theme.extend` fragment used by
tailwind.config.js:

- semantic colours, generated from the themes.xml roles and bound to the CSS
  variables emitted in config.ts;
- the scale tokens (spacing, radii, breakpoints, typography, shadow, motion).

The `color` palette is deliberately NOT emitted: it is internal, and what
Tailwind needs are the semantic colours built on top of it.
"""

from __future__ import annotations

from .common import *
from .config import _resolve_colour, _to_rgb_triplet, theme_role_ids
from .model import ManifestModel

_HEADER = [
    "// Generated by design/tools/sources/generate.py -- do not edit by hand.",
    "// Source of truth: design/tokens.xml + design/themes.xml",
    "// Tailwind/nativewind theme, consumed by tailwind.config.js.",
    "// Regenerate with: npm run design:gen",
]


def _js_str(value: object) -> str:
    text = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{text}'"


def _text(elem) -> str:
    return (elem.text or "").strip() if elem is not None else ""


def _values(token):
    values = token.find(q("values"))
    return values.findall(q("value")) if values is not None else []


def _scaled(values, unit: str, default_unit: str = "px"):
    unit = unit or default_unit
    return [(v.get("id") or "", _js_str(f"{_text(v)}{unit}")) for v in values]


def _shadow_entries(ctx: checker.RegistryModel, values):
    entries = []
    for v in values:
        ref = v.find(q("color") + "/" + q("ref"))
        hexv = _resolve_colour(ctx, _text(ref)) if ref is not None else "#000000"
        rgb = _to_rgb_triplet(hexv)
        x = _text(v.find(q("offset") + "/" + q("x"))) or "0"
        y = _text(v.find(q("offset") + "/" + q("y"))) or "0"
        radius = _text(v.find(q("radius"))) or "0"
        opacity = _text(v.find(q("opacity"))) or "1"
        entries.append((v.get("id") or "", _js_str(f"{x}px {y}px {radius}px rgb({rgb} / {opacity})")))
    return entries


def _entry(ctx: checker.RegistryModel, token):
    """Map one token to (tailwindKey, [(valueId, jsExpr)]), or None to skip."""
    tid = (token.get("id") or "").strip()
    unit = (token.get("unit") or "").strip()
    values = _values(token)
    if tid == "spacing":
        return "spacing", _scaled(values, unit)
    if tid == "radii":
        return "borderRadius", _scaled(values, unit)
    if tid == "breakpoints":
        return "screens", _scaled(values, unit)
    if tid == "family":
        items = []
        for v in values:
            families = [p.strip() for p in _text(v.find(q("web"))).split(",") if p.strip()]
            items.append((v.get("id") or "", "[" + ", ".join(_js_str(f) for f in families) + "]"))
        return "fontFamily", items
    if tid == "fontSizes":
        return "fontSize", _scaled(values, unit)
    if tid == "fontWeights":
        return "fontWeight", [(v.get("id") or "", _js_str(_text(v))) for v in values]
    if tid == "lineHeights":
        items = []
        for v in values:
            raw = _text(v)
            try:
                expr = _js_str(raw if float(raw) <= 2 else f"{raw}{unit or 'px'}")
            except ValueError:
                expr = _js_str(raw)
            items.append((v.get("id") or "", expr))
        return "lineHeight", items
    if tid == "letterSpacings":
        return "letterSpacing", _scaled(values, unit, "em")
    if tid == "shadow":
        return "boxShadow", _shadow_entries(ctx, values)
    if tid == "zIndex":
        return "zIndex", [(v.get("id") or "", _js_str(_text(v))) for v in values]
    if tid == "opacity":
        return "opacity", [(v.get("id") or "", _js_str(_text(v))) for v in values]
    if tid == "duration":
        return "transitionDuration", _scaled(values, unit or "ms", "ms")
    if tid == "easing":
        items = []
        for v in values:
            web = _text(v.find(q("web")))
            if not web or web == "spring":
                continue  # not a CSS timing function
            items.append((v.get("id") or "", _js_str(web)))
        return "transitionTimingFunction", items
    # `color` (palette) is skipped on purpose: semantic colours live in config.ts.
    return None


def render_tokens_theme(man: ManifestModel) -> str:
    tokens_path = man.ctx.catalog_files.get("tokens")
    if tokens_path is None or not tokens_path.exists():
        raise SystemExit("manifest: no tokens catalog file found")
    root = etree.parse(str(tokens_path)).getroot()
    groups: list[tuple[str, list[tuple[str, str]]]] = []
    # Semantic colours first: one Tailwind colour per themes.xml role, bound to
    # the CSS variable emitted in config.ts (so `bg-primary/50` keeps working).
    roles = theme_role_ids(man)
    if roles:
        groups.append(("colors", [
            (rid, _js_str(f"rgb(var(--{rid})/<alpha-value>)")) for rid in roles
        ]))
    for token in root.findall(q("items") + "/" + q("token")):
        entry = _entry(man.ctx, token)
        if entry is not None:
            groups.append(entry)
    lines = list(_HEADER)
    lines.append("module.exports = {")
    lines.append("  theme: {")
    for key, items in groups:
        lines.append(f"    {key}: {{")
        for ident, expr in items:
            lines.append(f"      {_js_str(ident)}: {expr},")
        lines.append("    },")
    lines.append("  },")
    lines.append("};")
    return "\n".join(lines) + "\n"
