// ==============================================================================
// FICHIER GENERÉ AUTOMATIQUEMENT - NE PAS MODIFIER MANUELLEMENT
// Modifiez foundation/theme/themes.yaml et relancez `npm run theme:generate`
// ==============================================================================

import { colors } from "../tokens";
import { createTheme } from "./createTheme";
import type { ColorScheme } from "./types";

export const themes = {
  autumn: createTheme({
    background: colors.autumn['background'],
    foreground: colors.autumn['text'],
    card: colors.autumn['surface'],
    cardForeground: colors.autumn['text'],
    primary: colors.autumn['primary'],
    primaryForeground: colors.white,
    secondary: colors.autumn['secondary'],
    secondaryForeground: colors.black,
    muted: colors.autumn['muted'],
    mutedForeground: colors.autumn['textSecondary'],
    accent: colors.autumn['accent'],
    accentForeground: colors.white,
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.autumn['border'],
    input: colors.autumn['surface'],
    ring: colors.autumn['primaryLight'],
    success: colors.autumn['success'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.info['500'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.autumn['primaryLight'], colors.autumn['primaryDark']],
      secondary: [colors.autumn['secondaryLight'], colors.autumn['secondaryDark']],
      success: [colors.autumn['successLight'], colors.autumn['success']],
      warning: [colors.warning['100'], colors.warning['600']],
      error: [colors.error['100'], colors.error['600']],
      info: [colors.info['100'], colors.info['600']],
      subtle: [colors.autumn['background'], colors.autumn['muted']],
      vibrant: [colors.autumn['accentLight'], colors.autumn['primary']],
    },
  }),
  christmas: createTheme({
    background: colors.christmas['background'],
    foreground: colors.christmas['text'],
    card: colors.christmas['surface'],
    cardForeground: colors.christmas['text'],
    primary: colors.christmas['primary'],
    primaryForeground: colors.white,
    secondary: colors.christmas['secondary'],
    secondaryForeground: colors.black,
    muted: colors.christmas['muted'],
    mutedForeground: colors.christmas['textSecondary'],
    accent: colors.christmas['accent'],
    accentForeground: colors.black,
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.christmas['border'],
    input: colors.christmas['surface'],
    ring: colors.christmas['primaryLight'],
    success: colors.christmas['success'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.info['500'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.christmas['primaryLight'], colors.christmas['primaryDark']],
      secondary: [colors.christmas['secondaryLight'], colors.christmas['secondaryDark']],
      success: [colors.christmas['successLight'], colors.christmas['success']],
      warning: [colors.warning['100'], colors.warning['600']],
      error: [colors.error['100'], colors.error['600']],
      info: [colors.info['100'], colors.info['600']],
      subtle: [colors.christmas['background'], colors.christmas['muted']],
      vibrant: [colors.christmas['accentLight'], colors.christmas['primary']],
    },
  }),
  dark: createTheme({
    background: colors.black,
    foreground: colors.white,
    card: colors.primary['900'],
    cardForeground: colors.gray['100'],
    primary: colors.primary['500'],
    primaryForeground: colors.white,
    secondary: colors.secondary['500'],
    secondaryForeground: colors.white,
    muted: colors.primary['900'],
    mutedForeground: colors.gray['500'],
    accent: colors.primary['900'],
    accentForeground: colors.primary['200'],
    destructive: colors.error['500'],
    destructiveForeground: colors.white,
    border: colors.primary['800'],
    input: colors.primary['900'],
    ring: colors.secondary['600'],
    success: colors.success['500'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.info['500'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.primary['800'], colors.black],
      secondary: [colors.secondary['900'], colors.black],
      vibrant: [colors.primary['800'], colors.secondary['900']],
      success: [colors.success['50'], colors.success['100']],
      warning: [colors.warning['50'], colors.warning['100']],
      error: [colors.error['50'], colors.error['100']],
      info: [colors.primary['50'], colors.primary['200']],
      subtle: [colors.primary['900'], colors.black],
    },
  }),
  halloween: createTheme({
    background: colors.halloween['background'],
    foreground: colors.halloween['text'],
    card: colors.halloween['surface'],
    cardForeground: colors.halloween['text'],
    primary: colors.halloween['primary'],
    primaryForeground: colors.black,
    secondary: colors.halloween['secondary'],
    secondaryForeground: colors.white,
    muted: colors.halloween['muted'],
    mutedForeground: colors.halloween['textSecondary'],
    accent: colors.halloween['accent'],
    accentForeground: colors.white,
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.halloween['border'],
    input: colors.halloween['surface'],
    ring: colors.halloween['primaryLight'],
    success: colors.halloween['success'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.info['500'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.halloween['primaryLight'], colors.halloween['primaryDark']],
      secondary: [colors.halloween['secondaryLight'], colors.halloween['secondaryDark']],
      success: [colors.halloween['successLight'], colors.halloween['success']],
      warning: [colors.warning['100'], colors.warning['600']],
      error: [colors.error['100'], colors.error['600']],
      info: [colors.info['100'], colors.info['600']],
      subtle: [colors.halloween['background'], colors.halloween['muted']],
      vibrant: [colors.halloween['accentLight'], colors.halloween['primary']],
    },
  }),
  light: createTheme({
    background: colors.white,
    foreground: colors.black,
    card: colors.primary['50'],
    cardForeground: colors.primary['900'],
    primary: colors.primary['500'],
    primaryForeground: colors.white,
    secondary: colors.secondary['500'],
    secondaryForeground: colors.white,
    muted: colors.gray['100'],
    mutedForeground: colors.gray['500'],
    accent: colors.secondary['50'],
    accentForeground: colors.secondary['700'],
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.primary['100'],
    input: colors.white,
    ring: colors.primary['500'],
    success: colors.success['600'],
    warning: colors.warning['600'],
    error: colors.error['600'],
    info: colors.info['600'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.primary['50'], colors.white],
      secondary: [colors.secondary['200'], colors.white],
      vibrant: [colors.primary['100'], colors.secondary['100']],
      success: [colors.success['50'], colors.success['100']],
      warning: [colors.warning['50'], colors.warning['100']],
      error: [colors.error['50'], colors.error['100']],
      info: [colors.primary['50'], colors.primary['200']],
      subtle: [colors.white, colors.primary['50']],
    },
  }),
  neon: createTheme({
    background: colors.neon['background'],
    foreground: colors.neon['text'],
    card: colors.neon['surface'],
    cardForeground: colors.neon['text'],
    primary: colors.neon['primary'],
    primaryForeground: colors.black,
    secondary: colors.neon['secondary'],
    secondaryForeground: colors.black,
    muted: colors.neon['muted'],
    mutedForeground: colors.neon['textSecondary'],
    accent: colors.neon['accent'],
    accentForeground: colors.white,
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.neon['border'],
    input: colors.neon['surface'],
    ring: colors.neon['primaryLight'],
    success: colors.neon['success'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.neon['secondary'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.neon['primaryLight'], colors.neon['primaryDark']],
      secondary: [colors.neon['secondaryLight'], colors.neon['secondaryDark']],
      success: [colors.neon['successLight'], colors.neon['success']],
      warning: [colors.warning['100'], colors.warning['600']],
      error: [colors.error['100'], colors.error['600']],
      info: [colors.neon['secondaryLight'], colors.neon['secondaryDark']],
      subtle: [colors.neon['background'], colors.neon['muted']],
      vibrant: [colors.neon['accentLight'], colors.neon['primary']],
    },
  }),
  spring: createTheme({
    background: colors.spring['background'],
    foreground: colors.spring['text'],
    card: colors.spring['surface'],
    cardForeground: colors.spring['text'],
    primary: colors.spring['primary'],
    primaryForeground: colors.white,
    secondary: colors.spring['secondary'],
    secondaryForeground: colors.white,
    muted: colors.spring['muted'],
    mutedForeground: colors.spring['textSecondary'],
    accent: colors.spring['accent'],
    accentForeground: colors.black,
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.spring['border'],
    input: colors.spring['surface'],
    ring: colors.spring['primaryLight'],
    success: colors.spring['success'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.info['500'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.spring['primaryLight'], colors.spring['primaryDark']],
      secondary: [colors.spring['secondaryLight'], colors.spring['secondaryDark']],
      success: [colors.spring['successLight'], colors.spring['success']],
      warning: [colors.warning['100'], colors.warning['600']],
      error: [colors.error['100'], colors.error['600']],
      info: [colors.info['100'], colors.info['600']],
      subtle: [colors.spring['background'], colors.spring['muted']],
      vibrant: [colors.spring['accentLight'], colors.spring['primary']],
    },
  }),
  summer: createTheme({
    background: colors.summer['background'],
    foreground: colors.summer['text'],
    card: colors.summer['surface'],
    cardForeground: colors.summer['text'],
    primary: colors.summer['primary'],
    primaryForeground: colors.white,
    secondary: colors.summer['secondary'],
    secondaryForeground: colors.white,
    muted: colors.summer['muted'],
    mutedForeground: colors.summer['textSecondary'],
    accent: colors.summer['accent'],
    accentForeground: colors.white,
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.summer['border'],
    input: colors.summer['surface'],
    ring: colors.summer['primaryLight'],
    success: colors.summer['success'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.info['500'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.summer['primaryLight'], colors.summer['primaryDark']],
      secondary: [colors.summer['secondaryLight'], colors.summer['secondaryDark']],
      success: [colors.summer['successLight'], colors.summer['success']],
      warning: [colors.warning['100'], colors.warning['600']],
      error: [colors.error['100'], colors.error['600']],
      info: [colors.info['100'], colors.info['600']],
      subtle: [colors.summer['background'], colors.summer['muted']],
      vibrant: [colors.summer['accentLight'], colors.summer['primary']],
    },
  }),
  winter: createTheme({
    background: colors.winter['background'],
    foreground: colors.winter['text'],
    card: colors.winter['surface'],
    cardForeground: colors.winter['text'],
    primary: colors.winter['primary'],
    primaryForeground: colors.white,
    secondary: colors.winter['secondary'],
    secondaryForeground: colors.black,
    muted: colors.winter['muted'],
    mutedForeground: colors.winter['textSecondary'],
    accent: colors.winter['accent'],
    accentForeground: colors.white,
    destructive: colors.error['600'],
    destructiveForeground: colors.white,
    border: colors.winter['border'],
    input: colors.winter['surface'],
    ring: colors.winter['primaryLight'],
    success: colors.winter['success'],
    warning: colors.warning['500'],
    error: colors.error['500'],
    info: colors.info['500'],
    transparent: colors.transparent,
    gradients: {
      primary: [colors.winter['primaryLight'], colors.winter['primaryDark']],
      secondary: [colors.winter['secondaryLight'], colors.winter['secondaryDark']],
      success: [colors.winter['successLight'], colors.winter['success']],
      warning: [colors.warning['100'], colors.warning['600']],
      error: [colors.error['100'], colors.error['600']],
      info: [colors.info['100'], colors.info['600']],
      subtle: [colors.winter['background'], colors.winter['muted']],
      vibrant: [colors.winter['accentLight'], colors.winter['primary']],
    },
  }),
} as const;

export type ThemeName = keyof typeof themes;
