import type { BlockMeta } from "../../types";

export const newBlocks: BlockMeta[] = [
  {
    id: "SocialLinksBlock",
    label: "Social Links",
    description: "Row of social network icon buttons with optional labels and customizable layout.",
    category: "social",
    tags: ["social", "links", "icons", "network", "share"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary" },
    components: ["Pressable"],
    slots: [],
    props: [
      { name: "links",        label: "Links",         type: "string",  group: "content" },
      { name: "direction",    label: "Direction",     type: "enum",    group: "layout",   default: "row",        options: ["row", "column"] },
      { name: "size",         label: "Size",          type: "enum",    group: "style",    default: "md",         options: ["sm", "md", "lg"] },
      { name: "variant",      label: "Variant",       type: "enum",    group: "style",    default: "icon",       options: ["icon", "icon-label", "label"] },
      { name: "spacing",      label: "Spacing",       type: "spacing", group: "layout",   default: 2 },
      { name: "color",        label: "Color",         type: "color",   group: "style",    themeDefault: "foreground" },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "full" },
      { name: "showLabels",   label: "Show labels",   type: "boolean", group: "behavior", default: false },
    ],
  },
  {
    id: "ProductCardBlock",
    label: "Product Card",
    description: "E-commerce product card with image, name, price, rating, and add-to-cart button.",
    category: "ecommerce",
    tags: ["product", "card", "ecommerce", "shop", "price", "rating"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", muted: "mutedForeground" },
    components: ["Button", "Badge"],
    slots: [
      { name: "image", label: "Product image", required: false, kind: "named" },
    ],
    props: [
      { name: "name",          label: "Name",           type: "string",  group: "content" },
      { name: "price",         label: "Price",          type: "string",  group: "content" },
      { name: "originalPrice", label: "Original price", type: "string",  group: "content" },
      { name: "imageUrl",      label: "Image URL",      type: "string",  group: "content" },
      { name: "rating",        label: "Rating",         type: "number",  group: "content" },
      { name: "reviewCount",   label: "Review count",   type: "number",  group: "content" },
      { name: "badge",         label: "Badge",          type: "string",  group: "content" },
      { name: "inStock",       label: "In stock",       type: "boolean", group: "behavior", default: true },
      { name: "background",    label: "Background",     type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius",  label: "Border radius",  type: "radius",  group: "style",    default: "xl" },
      { name: "padding",       label: "Padding",        type: "spacing", group: "layout",   default: 3 },
      { name: "shadow",        label: "Shadow",         type: "shadow",  group: "style",    default: "sm" },
    ],
  },
  {
    id: "NotificationItemBlock",
    label: "Notification Item",
    description: "Notification row with icon, title, body, timestamp, and read state.",
    category: "feedback",
    tags: ["notification", "alert", "item", "row", "unread"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", border: "border" },
    components: ["IconButton"],
    slots: [],
    props: [
      { name: "title",       label: "Title",        type: "string",  group: "content" },
      { name: "body",        label: "Body",         type: "string",  group: "content" },
      { name: "timestamp",   label: "Timestamp",    type: "string",  group: "content" },
      { name: "read",        label: "Read",         type: "boolean", group: "behavior", default: false },
      { name: "iconName",    label: "Icon name",    type: "string",  group: "content",  default: "bell" },
      { name: "iconColor",   label: "Icon color",   type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "card" },
      { name: "padding",     label: "Padding",      type: "spacing", group: "layout",   default: 3 },
      { name: "showDivider", label: "Show divider", type: "boolean", group: "style",    default: true },
      { name: "pressable",   label: "Pressable",    type: "boolean", group: "behavior", default: true },
    ],
  },
  {
    id: "PricingCardBlock",
    label: "Pricing Card",
    description: "Pricing plan card with features list, price, period, and CTA button.",
    category: "ecommerce",
    tags: ["pricing", "plan", "card", "subscription", "features"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary" },
    components: ["Button", "Badge"],
    slots: [],
    props: [
      { name: "planName",     label: "Plan name",     type: "string",  group: "content" },
      { name: "price",        label: "Price",         type: "string",  group: "content" },
      { name: "period",       label: "Period",        type: "string",  group: "content",  default: "mo" },
      { name: "description",  label: "Description",   type: "string",  group: "content" },
      { name: "features",     label: "Features",      type: "string",  group: "content" },
      { name: "ctaLabel",     label: "CTA label",     type: "string",  group: "content",  default: "Get started" },
      { name: "highlighted",  label: "Highlighted",   type: "boolean", group: "style",    default: false },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "accentColor",  label: "Accent color",  type: "color",   group: "style",    themeDefault: "primary" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "xl" },
      { name: "padding",      label: "Padding",       type: "spacing", group: "layout",   default: 5 },
      { name: "spacing",      label: "Spacing",       type: "spacing", group: "layout",   default: 3 },
      { name: "shadow",       label: "Shadow",        type: "shadow",  group: "style",    default: "md" },
    ],
  },
  {
    id: "TransactionItemBlock",
    label: "Transaction Item",
    description: "Financial transaction row with icon, merchant, amount, date, and status badge.",
    category: "finance",
    tags: ["transaction", "finance", "payment", "row", "amount"],
    themeMapping: { bg: "card", text: "foreground", border: "border", muted: "mutedForeground" },
    components: [],
    slots: [],
    props: [
      { name: "merchant",    label: "Merchant",     type: "string",  group: "content" },
      { name: "category",    label: "Category",     type: "string",  group: "content" },
      { name: "amount",      label: "Amount",       type: "string",  group: "content" },
      { name: "date",        label: "Date",         type: "string",  group: "content" },
      { name: "type",        label: "Type",         type: "enum",    group: "behavior", default: "debit",     options: ["debit", "credit"] },
      { name: "status",      label: "Status",       type: "enum",    group: "behavior", default: "completed", options: ["completed", "pending", "failed"] },
      { name: "iconName",    label: "Icon name",    type: "string",  group: "content",  default: "credit-card" },
      { name: "iconColor",   label: "Icon color",   type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "card" },
      { name: "padding",     label: "Padding",      type: "spacing", group: "layout",   default: 3 },
      { name: "showDivider", label: "Show divider", type: "boolean", group: "style",    default: true },
    ],
  },
  {
    id: "OnboardingSlideBlock",
    label: "Onboarding Slide",
    description: "Single onboarding slide with illustration, title, description, dots, and CTA.",
    category: "onboarding",
    tags: ["onboarding", "slide", "intro", "welcome", "tutorial"],
    themeMapping: { bg: "background", text: "foreground", accent: "primary" },
    components: ["Button"],
    slots: [
      { name: "illustration", label: "Illustration", required: false, kind: "named" },
    ],
    props: [
      { name: "title",        label: "Title",         type: "string",  group: "content" },
      { name: "description",  label: "Description",   type: "string",  group: "content" },
      { name: "totalSlides",  label: "Total slides",  type: "number",  group: "behavior", default: 3 },
      { name: "currentSlide", label: "Current slide", type: "number",  group: "behavior", default: 0 },
      { name: "ctaLabel",     label: "CTA label",     type: "string",  group: "content",  default: "Get started" },
      { name: "skipLabel",    label: "Skip label",    type: "string",  group: "content",  default: "Skip" },
      { name: "accentColor",  label: "Accent color",  type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "background" },
      { name: "padding",      label: "Padding",       type: "spacing", group: "layout",   default: 6 },
    ],
  },
  {
    id: "ChatBubbleBlock",
    label: "Chat Bubble",
    description: "Chat message bubble with sender/receiver layout, timestamp, and read status.",
    category: "messaging",
    tags: ["chat", "message", "bubble", "conversation", "messaging"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", muted: "mutedForeground" },
    components: ["Avatar"],
    slots: [],
    props: [
      { name: "message",     label: "Message",      type: "string",  group: "content" },
      { name: "timestamp",   label: "Timestamp",    type: "string",  group: "content" },
      { name: "isSent",      label: "Is sent",      type: "boolean", group: "behavior", default: false },
      { name: "isRead",      label: "Is read",      type: "boolean", group: "behavior", default: false },
      { name: "senderName",  label: "Sender name",  type: "string",  group: "content" },
      { name: "avatarUrl",   label: "Avatar URL",   type: "string",  group: "content" },
      { name: "showAvatar",  label: "Show avatar",  type: "boolean", group: "behavior", default: true },
      { name: "accentColor", label: "Accent color", type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "card" },
      { name: "maxWidth",    label: "Max width",    type: "number",  group: "layout",   default: 280 },
    ],
  },
  {
    id: "CalendarEventBlock",
    label: "Calendar Event",
    description: "Event card with date badge, title, time range, location, and attendee count.",
    category: "calendar",
    tags: ["calendar", "event", "date", "schedule", "meeting"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", muted: "mutedForeground" },
    components: [],
    slots: [],
    props: [
      { name: "title",         label: "Title",          type: "string",  group: "content" },
      { name: "date",          label: "Date",           type: "string",  group: "content" },
      { name: "dayNumber",     label: "Day number",     type: "string",  group: "content" },
      { name: "month",         label: "Month",          type: "string",  group: "content" },
      { name: "startTime",     label: "Start time",     type: "string",  group: "content" },
      { name: "endTime",       label: "End time",       type: "string",  group: "content" },
      { name: "location",      label: "Location",       type: "string",  group: "content" },
      { name: "attendeeCount", label: "Attendee count", type: "number",  group: "content" },
      { name: "color",         label: "Color",          type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",    label: "Background",     type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius",  label: "Border radius",  type: "radius",  group: "style",    default: "xl" },
      { name: "padding",       label: "Padding",        type: "spacing", group: "layout",   default: 3 },
    ],
  },
  {
    id: "FileItemBlock",
    label: "File Item",
    description: "File list item with icon, name, size, type badge, and download/delete actions.",
    category: "files",
    tags: ["file", "item", "row", "document", "attachment"],
    themeMapping: { bg: "card", text: "foreground", border: "border", muted: "mutedForeground" },
    components: [],
    slots: [],
    props: [
      { name: "name",        label: "Name",         type: "string",  group: "content" },
      { name: "size",        label: "Size",         type: "string",  group: "content" },
      { name: "type",        label: "Type",         type: "string",  group: "content" },
      { name: "updatedAt",   label: "Updated at",   type: "string",  group: "content" },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "card" },
      { name: "padding",     label: "Padding",      type: "spacing", group: "layout",   default: 3 },
      { name: "showDivider", label: "Show divider", type: "boolean", group: "style",    default: true },
      { name: "pressable",   label: "Pressable",    type: "boolean", group: "behavior", default: true },
    ],
  },
  {
    id: "ContactCardBlock",
    label: "Contact Card",
    description: "Contact card with avatar, name, role, company, and action buttons (call, email, web).",
    category: "profile",
    tags: ["contact", "card", "profile", "person", "address-book"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", muted: "mutedForeground" },
    components: ["Avatar"],
    slots: [],
    props: [
      { name: "name",         label: "Name",          type: "string",  group: "content" },
      { name: "role",         label: "Role",          type: "string",  group: "content" },
      { name: "company",      label: "Company",       type: "string",  group: "content" },
      { name: "avatarUrl",    label: "Avatar URL",    type: "string",  group: "content" },
      { name: "initials",     label: "Initials",      type: "string",  group: "content" },
      { name: "phone",        label: "Phone",         type: "string",  group: "content" },
      { name: "email",        label: "Email",         type: "string",  group: "content" },
      { name: "website",      label: "Website",       type: "string",  group: "content" },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "accentColor",  label: "Accent color",  type: "color",   group: "style",    themeDefault: "primary" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "xl" },
      { name: "padding",      label: "Padding",       type: "spacing", group: "layout",   default: 4 },
      { name: "showActions",  label: "Show actions",  type: "boolean", group: "behavior", default: true },
    ],
  },
  {
    id: "MapPinBlock",
    label: "Map Pin",
    description: "Location display card with address, coordinates, and open-in-maps action.",
    category: "location",
    tags: ["map", "location", "address", "pin", "geo"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", border: "border" },
    components: [],
    slots: [],
    props: [
      { name: "address",         label: "Address",          type: "string",  group: "content" },
      { name: "city",            label: "City",             type: "string",  group: "content" },
      { name: "country",         label: "Country",          type: "string",  group: "content" },
      { name: "latitude",        label: "Latitude",         type: "number",  group: "content" },
      { name: "longitude",       label: "Longitude",        type: "number",  group: "content" },
      { name: "label",           label: "Label",            type: "string",  group: "content" },
      { name: "background",      label: "Background",       type: "color",   group: "style",    themeDefault: "card" },
      { name: "accentColor",     label: "Accent color",     type: "color",   group: "style",    themeDefault: "primary" },
      { name: "borderRadius",    label: "Border radius",    type: "radius",  group: "style",    default: "xl" },
      { name: "padding",         label: "Padding",          type: "spacing", group: "layout",   default: 3 },
      { name: "showCoordinates", label: "Show coordinates", type: "boolean", group: "behavior", default: false },
      { name: "showOpenButton",  label: "Show open button", type: "boolean", group: "behavior", default: true },
    ],
  },
  {
    id: "PasswordStrengthBlock",
    label: "Password Strength",
    description: "Password input with strength meter and requirements checklist.",
    category: "form",
    tags: ["password", "strength", "input", "form", "security"],
    themeMapping: { bg: "input", text: "foreground", border: "border", muted: "mutedForeground" },
    components: ["TextInput"],
    slots: [],
    props: [
      { name: "value",            label: "Value",             type: "string",  group: "content" },
      { name: "label",            label: "Label",             type: "string",  group: "content",  default: "Password" },
      { name: "placeholder",      label: "Placeholder",       type: "string",  group: "content",  default: "Enter password" },
      { name: "showRequirements", label: "Show requirements", type: "boolean", group: "behavior", default: true },
      { name: "background",       label: "Background",        type: "color",   group: "style",    themeDefault: "input" },
      { name: "borderRadius",     label: "Border radius",     type: "radius",  group: "style",    default: "lg" },
    ],
  },
  {
    id: "MediaPickerBlock",
    label: "Media Picker",
    description: "Image/video picker with preview grid and add button.",
    category: "media",
    tags: ["media", "picker", "image", "video", "upload", "gallery"],
    themeMapping: { bg: "muted", text: "foreground", accent: "primary" },
    components: [],
    slots: [],
    props: [
      { name: "items",       label: "Items",        type: "string",  group: "content" },
      { name: "maxItems",    label: "Max items",    type: "number",  group: "behavior", default: 9 },
      { name: "label",       label: "Label",        type: "string",  group: "content" },
      { name: "columns",     label: "Columns",      type: "number",  group: "layout",   default: 3 },
      { name: "itemSize",    label: "Item size",    type: "number",  group: "layout",   default: 100 },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "muted" },
      { name: "accentColor", label: "Accent color", type: "color",   group: "style",    themeDefault: "primary" },
    ],
  },
  {
    id: "BannerBlock",
    label: "Banner",
    description: "Dismissible info/warning/error/success banner with icon and optional action.",
    category: "feedback",
    tags: ["banner", "alert", "info", "warning", "error", "success"],
    themeMapping: { text: "foreground", border: "border" },
    components: [],
    slots: [],
    props: [
      { name: "type",         label: "Type",          type: "enum",    group: "style",    default: "info", options: ["info", "success", "warning", "error"] },
      { name: "title",        label: "Title",         type: "string",  group: "content" },
      { name: "message",      label: "Message",       type: "string",  group: "content" },
      { name: "actionLabel",  label: "Action label",  type: "string",  group: "content" },
      { name: "dismissible",  label: "Dismissible",   type: "boolean", group: "behavior", default: true },
      { name: "icon",         label: "Icon",          type: "string",  group: "content" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "lg" },
      { name: "padding",      label: "Padding",       type: "spacing", group: "layout",   default: 3 },
    ],
  },
  {
    id: "CommentBlock",
    label: "Comment",
    description: "Comment/review item with avatar, author, content, timestamp, and like/reply actions.",
    category: "social",
    tags: ["comment", "review", "social", "like", "reply"],
    themeMapping: { bg: "card", text: "foreground", border: "border", muted: "mutedForeground" },
    components: ["Avatar"],
    slots: [],
    props: [
      { name: "author",      label: "Author",       type: "string",  group: "content" },
      { name: "avatarUrl",   label: "Avatar URL",   type: "string",  group: "content" },
      { name: "initials",    label: "Initials",     type: "string",  group: "content" },
      { name: "content",     label: "Content",      type: "string",  group: "content" },
      { name: "timestamp",   label: "Timestamp",    type: "string",  group: "content" },
      { name: "likeCount",   label: "Like count",   type: "number",  group: "content",  default: 0 },
      { name: "liked",       label: "Liked",        type: "boolean", group: "behavior", default: false },
      { name: "replyCount",  label: "Reply count",  type: "number",  group: "content",  default: 0 },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "card" },
      { name: "padding",     label: "Padding",      type: "spacing", group: "layout",   default: 3 },
      { name: "showDivider", label: "Show divider", type: "boolean", group: "style",    default: true },
    ],
  },
  {
    id: "OTPInputBlock",
    label: "OTP Input",
    description: "One-time password input with N digit boxes and auto-focus progression.",
    category: "form",
    tags: ["otp", "code", "input", "verification", "form"],
    themeMapping: { bg: "input", text: "foreground", accent: "primary", border: "border" },
    components: ["TextInput"],
    slots: [],
    props: [
      { name: "length",      label: "Length",       type: "number",  group: "behavior", default: 6 },
      { name: "label",       label: "Label",        type: "string",  group: "content" },
      { name: "error",       label: "Error",        type: "string",  group: "content" },
      { name: "disabled",    label: "Disabled",     type: "boolean", group: "behavior", default: false },
      { name: "size",        label: "Size",         type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "accentColor", label: "Accent color", type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "input" },
    ],
  },
  {
    id: "TagInputBlock",
    label: "Tag Input",
    description: "Input field that creates removable tags/chips on Enter.",
    category: "form",
    tags: ["tag", "chip", "input", "form", "multi-select"],
    themeMapping: { bg: "input", text: "foreground", accent: "primary", border: "border" },
    components: ["TextInput"],
    slots: [],
    props: [
      { name: "tags",         label: "Tags",          type: "string",  group: "content" },
      { name: "placeholder",  label: "Placeholder",   type: "string",  group: "content",  default: "Add tag..." },
      { name: "label",        label: "Label",         type: "string",  group: "content" },
      { name: "maxTags",      label: "Max tags",      type: "number",  group: "behavior", default: 10 },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "input" },
      { name: "tagColor",     label: "Tag color",     type: "color",   group: "style",    themeDefault: "primary" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "lg" },
    ],
  },
  {
    id: "StepperBlock",
    label: "Stepper",
    description: "Multi-step progress indicator with labels, descriptions, and active state.",
    category: "navigation",
    tags: ["stepper", "steps", "progress", "wizard", "navigation"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", border: "border" },
    components: [],
    slots: [],
    props: [
      { name: "steps",            label: "Steps",             type: "string",  group: "content" },
      { name: "currentStep",      label: "Current step",      type: "number",  group: "behavior", default: 0 },
      { name: "orientation",      label: "Orientation",       type: "enum",    group: "layout",   default: "horizontal", options: ["horizontal", "vertical"] },
      { name: "accentColor",      label: "Accent color",      type: "color",   group: "style",    themeDefault: "primary" },
      { name: "completedColor",   label: "Completed color",   type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",       label: "Background",        type: "color",   group: "style",    themeDefault: "card" },
      { name: "showLabels",       label: "Show labels",       type: "boolean", group: "behavior", default: true },
      { name: "showDescriptions", label: "Show descriptions", type: "boolean", group: "behavior", default: false },
      { name: "size",             label: "Size",              type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
    ],
  },
  {
    id: "RatingBlock",
    label: "Rating",
    description: "Star rating input or display with configurable max stars and colors.",
    category: "feedback",
    tags: ["rating", "stars", "review", "score", "feedback"],
    themeMapping: { text: "foreground", muted: "mutedForeground" },
    components: [],
    slots: [],
    props: [
      { name: "value",         label: "Value",          type: "number",  group: "content",  default: 0 },
      { name: "maxStars",      label: "Max stars",      type: "number",  group: "behavior", default: 5 },
      { name: "readonly",      label: "Readonly",       type: "boolean", group: "behavior", default: false },
      { name: "size",          label: "Size",           type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "activeColor",   label: "Active color",   type: "color",   group: "style",    default: "#f59e0b" },
      { name: "inactiveColor", label: "Inactive color", type: "color",   group: "style",    themeDefault: "muted" },
      { name: "showValue",     label: "Show value",     type: "boolean", group: "behavior", default: false },
      { name: "label",         label: "Label",          type: "string",  group: "content" },
    ],
  },
  {
    id: "QuoteBlock",
    label: "Quote",
    description: "Stylized quote/testimonial with author, avatar, and accent bar.",
    category: "content",
    tags: ["quote", "testimonial", "blockquote", "author", "review"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", muted: "mutedForeground" },
    components: ["Avatar"],
    slots: [],
    props: [
      { name: "quote",          label: "Quote",           type: "string",  group: "content" },
      { name: "author",         label: "Author",          type: "string",  group: "content" },
      { name: "role",           label: "Role",            type: "string",  group: "content" },
      { name: "avatarUrl",      label: "Avatar URL",      type: "string",  group: "content" },
      { name: "accentColor",    label: "Accent color",    type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",     label: "Background",      type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius",   label: "Border radius",   type: "radius",  group: "style",    default: "xl" },
      { name: "padding",        label: "Padding",         type: "spacing", group: "layout",   default: 4 },
      { name: "showQuoteIcon",  label: "Show quote icon", type: "boolean", group: "behavior", default: true },
      { name: "variant",        label: "Variant",         type: "enum",    group: "style",    default: "card", options: ["left-bar", "card", "minimal"] },
    ],
  },
  {
    id: "TimelineBlock",
    label: "Timeline",
    description: "Vertical timeline with events, icons, timestamps, and connector lines.",
    category: "content",
    tags: ["timeline", "events", "history", "steps", "vertical"],
    themeMapping: { text: "foreground", accent: "primary", border: "border", muted: "mutedForeground" },
    components: [],
    slots: [],
    props: [
      { name: "events",        label: "Events",         type: "string",  group: "content" },
      { name: "accentColor",   label: "Accent color",   type: "color",   group: "style",    themeDefault: "primary" },
      { name: "lineColor",     label: "Line color",     type: "color",   group: "style",    themeDefault: "border" },
      { name: "spacing",       label: "Spacing",        type: "spacing", group: "layout",   default: 3 },
      { name: "showConnector", label: "Show connector", type: "boolean", group: "behavior", default: true },
    ],
  },
  {
    id: "CounterBlock",
    label: "Counter",
    description: "Number counter with increment/decrement controls, min/max bounds, and step.",
    category: "form",
    tags: ["counter", "number", "input", "increment", "decrement"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", border: "border" },
    components: [],
    slots: [],
    props: [
      { name: "value",       label: "Value",        type: "number",  group: "content",  default: 0 },
      { name: "min",         label: "Min",          type: "number",  group: "behavior", default: 0 },
      { name: "max",         label: "Max",          type: "number",  group: "behavior", default: 100 },
      { name: "step",        label: "Step",         type: "number",  group: "behavior", default: 1 },
      { name: "label",       label: "Label",        type: "string",  group: "content" },
      { name: "size",        label: "Size",         type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "accentColor", label: "Accent color", type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "card" },
      { name: "disabled",    label: "Disabled",     type: "boolean", group: "behavior", default: false },
    ],
  },
  {
    id: "SegmentedControlBlock",
    label: "Segmented Control",
    description: "iOS-style segmented control / tab switcher with customizable colors and sizes.",
    category: "navigation",
    tags: ["segmented", "control", "tabs", "switcher", "navigation"],
    themeMapping: { bg: "muted", text: "foreground", accent: "primary" },
    components: [],
    slots: [],
    props: [
      { name: "segments",          label: "Segments",           type: "string",  group: "content" },
      { name: "value",             label: "Value",              type: "string",  group: "behavior" },
      { name: "background",        label: "Background",         type: "color",   group: "style",    themeDefault: "muted" },
      { name: "activeBackground",  label: "Active background",  type: "color",   group: "style",    themeDefault: "card" },
      { name: "activeColor",       label: "Active color",       type: "color",   group: "style",    themeDefault: "foreground" },
      { name: "inactiveColor",     label: "Inactive color",     type: "color",   group: "style",    themeDefault: "mutedForeground" },
      { name: "size",              label: "Size",               type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "fullWidth",         label: "Full width",         type: "boolean", group: "layout",   default: false },
    ],
  },
];
