/**
 * Property 8 : `openURL` dans le code généré est toujours précédé d'une validation
 *
 * Validates: Requirements 3.6
 *
 * For any ActionDef of type 'openURL', the code generated by the generator must:
 *   1. Contain `isSafeUrl`
 *   2. Contain `Linking.openURL`
 *   3. Have `isSafeUrl` appear BEFORE `Linking.openURL` in the generated string
 *
 * The handler body (containing the openURL guard) is generated in the hook file
 * via generatePageHook. We test both generatePageHook and generatePageCode.
 *
 * Also tests generatePageCode: for any PageDocument containing an openURL action,
 * the combined generated output (hook + component) must contain `isSafeUrl`.
 */

import { describe, it, expect } from "vitest";
import * as fc from "fast-check";
import { generatePageCode, generatePageHook } from "../generator";
import type { PageDocument, TreeNode } from "../../tree/types";

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** Generate a valid node id */
const arbNodeId = fc.stringMatching(/^n_[a-z0-9]{4,8}$/);

/** Generate a URL string (any string — the guard must handle all cases) */
const arbUrl: fc.Arbitrary<string> = fc.oneof(
  fc.constant("https://example.com"),
  fc.constant("http://example.com/path"),
  fc.constant("mailto:user@example.com"),
  fc.constant("tel:+33612345678"),
  fc.constant("javascript:alert(1)"),
  fc.constant("data:text/html,<script>alert(1)</script>"),
  fc.constant(""),
  fc.constant("not-a-url"),
  fc.stringMatching(/^[a-z]{2,8}:\/\/[a-z]{3,10}\.[a-z]{2,4}\/[a-z]{0,10}$/),
  fc.string({ minLength: 0, maxLength: 50 })
);

/** Generate a minimal leaf TreeNode with an openURL event */
const arbLeafNodeWithOpenURL: fc.Arbitrary<TreeNode> = fc
  .record({
    id: arbNodeId,
    url: arbUrl,
  })
  .map(({ id, url }) => ({
    id,
    kind: "component" as const,
    registryId: "Button",
    props: { label: "Open" },
    children: [],
    events: {
      onPress: [
        {
          type: "openURL" as const,
          payload: { url },
        },
      ],
    },
  }));

/** Generate a PageDocument whose root contains an openURL action */
const arbPageWithOpenURL: fc.Arbitrary<PageDocument> = fc
  .record({
    id: fc.uuid(),
    name: fc.stringMatching(/^[A-Z][a-zA-Z]{2,15}Screen$/),
    route: fc.stringMatching(/^[a-z][a-z-]{2,15}$/),
    root: arbLeafNodeWithOpenURL,
  })
  .map(({ id, name, route, root }) => ({
    id,
    name,
    route,
    root,
    state: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }));

// ---------------------------------------------------------------------------
// Helper: generate the hook code for a page with an openURL action
// The handler body (with the isSafeUrl guard) lives in the hook file.
// ---------------------------------------------------------------------------

function buildPageWithOpenURL(url: string): PageDocument {
  return {
    id: "test-page-id",
    name: "TestScreen",
    route: "test-screen",
    root: {
      id: "n_root01",
      kind: "component",
      registryId: "Button",
      props: { label: "Open" },
      children: [],
      events: {
        onPress: [{ type: "openURL", payload: { url } }],
      },
    },
    state: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Property 8.1 — Hook generated for openURL always contains isSafeUrl
// ---------------------------------------------------------------------------

describe("Property 8 — openURL dans le hook généré contient isSafeUrl", () => {
  /**
   * **Validates: Requirements 3.6**
   *
   * For any ActionDef with type 'openURL' and any URL payload,
   * the hook generated by generatePageHook must contain `isSafeUrl`.
   */
  it("le hook généré contient isSafeUrl pour toute URL", () => {
    fc.assert(
      fc.property(arbUrl, (url) => {
        const page = buildPageWithOpenURL(url);
        const hook = generatePageHook(page);
        return hook.includes("isSafeUrl");
      }),
      { numRuns: 300 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 8.2 — Hook generated for openURL always contains Linking.openURL
// ---------------------------------------------------------------------------

describe("Property 8 — openURL dans le hook généré contient Linking.openURL", () => {
  /**
   * **Validates: Requirements 3.6**
   *
   * For any ActionDef with type 'openURL' and any URL payload,
   * the hook generated by generatePageHook must contain `Linking.openURL`.
   */
  it("le hook généré contient Linking.openURL pour toute URL", () => {
    fc.assert(
      fc.property(arbUrl, (url) => {
        const page = buildPageWithOpenURL(url);
        const hook = generatePageHook(page);
        return hook.includes("Linking.openURL");
      }),
      { numRuns: 300 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 8.3 — isSafeUrl appears BEFORE Linking.openURL in the hook
// ---------------------------------------------------------------------------

describe("Property 8 — isSafeUrl précède Linking.openURL dans le hook généré", () => {
  /**
   * **Validates: Requirements 3.6**
   *
   * The `isSafeUrl` guard must appear before any call to `Linking.openURL`
   * in the generated hook string.
   */
  it("isSafeUrl apparaît avant Linking.openURL pour toute URL", () => {
    fc.assert(
      fc.property(arbUrl, (url) => {
        const page = buildPageWithOpenURL(url);
        const hook = generatePageHook(page);
        const isSafeUrlIdx = hook.indexOf("isSafeUrl");
        const linkingOpenURLIdx = hook.indexOf("Linking.openURL");
        // Both must be present
        if (isSafeUrlIdx === -1 || linkingOpenURLIdx === -1) return false;
        // isSafeUrl must come before Linking.openURL
        return isSafeUrlIdx < linkingOpenURLIdx;
      }),
      { numRuns: 300 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 8.4 — generatePageHook with openURL action always contains isSafeUrl
// ---------------------------------------------------------------------------

describe("Property 8 — generatePageHook avec openURL contient isSafeUrl", () => {
  /**
   * **Validates: Requirements 3.6**
   *
   * For any PageDocument containing an openURL action,
   * generatePageHook must contain `isSafeUrl`.
   */
  it("generatePageHook contient isSafeUrl pour tout PageDocument avec openURL", () => {
    fc.assert(
      fc.property(arbPageWithOpenURL, (page) => {
        const hook = generatePageHook(page);
        return hook.includes("isSafeUrl");
      }),
      { numRuns: 200 }
    );
  });
});

// ---------------------------------------------------------------------------
// Concrete examples — quick sanity checks
// ---------------------------------------------------------------------------

describe("openURL codegen — exemples concrets", () => {
  it("génère un guard isSafeUrl pour une URL https", () => {
    const hook = generatePageHook(buildPageWithOpenURL("https://example.com"));
    expect(hook).toContain("isSafeUrl");
    expect(hook).toContain("Linking.openURL");
    expect(hook.indexOf("isSafeUrl")).toBeLessThan(hook.indexOf("Linking.openURL"));
  });

  it("génère un guard isSafeUrl pour une URL javascript:", () => {
    const hook = generatePageHook(buildPageWithOpenURL("javascript:alert(1)"));
    expect(hook).toContain("isSafeUrl");
    expect(hook).toContain("Linking.openURL");
    expect(hook.indexOf("isSafeUrl")).toBeLessThan(hook.indexOf("Linking.openURL"));
  });

  it("génère un guard isSafeUrl pour une URL vide", () => {
    const hook = generatePageHook(buildPageWithOpenURL(""));
    expect(hook).toContain("isSafeUrl");
    expect(hook).toContain("Linking.openURL");
    expect(hook.indexOf("isSafeUrl")).toBeLessThan(hook.indexOf("Linking.openURL"));
  });

  it("le hook généré a la forme if (isSafeUrl(...)) Linking.openURL(...)", () => {
    const hook = generatePageHook(buildPageWithOpenURL("https://example.com"));
    expect(hook).toMatch(/if\s*\(isSafeUrl\(/);
    expect(hook).toMatch(/Linking\.openURL\(/);
  });

  it("generatePageHook avec openURL contient isSafeUrl", () => {
    const page: PageDocument = {
      id: "p1",
      name: "HomeScreen",
      route: "home",
      root: {
        id: "n_btn01",
        kind: "component",
        registryId: "Button",
        props: {},
        children: [],
        events: {
          onPress: [{ type: "openURL", payload: { url: "https://flipova.io" } }],
        },
      },
      state: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    const hook = generatePageHook(page);
    expect(hook).toContain("isSafeUrl");
    expect(hook).toContain("Linking.openURL");
  });
});
