/**
 * Controller: getusers
 * Service: jsonplaceholder — GET /users
 *
 * Auto-generated by Flipova Studio. Do not edit manually.
 */
import { useState, useEffect, useCallback } from "react";
import { jsonplaceholder } from "../services/jsonplaceholder";

export interface GetusersState<T = any> {
  data: T | null;
  loading: boolean;
  error: string | null;
  /** Call with optional body override for POST/PUT/PATCH queries */
  refetch: (body?: Record<string, any>) => Promise<T | null>;
}

export function useGetusers<T = any>(): GetusersState<T> {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const refetch = useCallback(async (body?: Record<string, any>): Promise<T | null> => {
    setLoading(true);
    setError(null);
    try {
      const result = await jsonplaceholder.get<T>("/users", body);
      setData(result);
      return result;
    } catch (e: any) {
      setError(e.message || "Request failed");
      throw e;
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { refetch(); }, [refetch]);

  return { data, loading, error, refetch };
}
