/**
 * Component Registry
 *
 * Base UI components: buttons, inputs, badges, avatars, etc.
 * Each component supports variants (e.g. primary/secondary/ghost for buttons)
 * and sizes. Theme-aware via themeDefault on color props.
 */

import type { ComponentMeta } from "../types";

export function getComponentMeta(id: string): ComponentMeta | undefined {
  return componentRegistry.find((m) => m.id === id);
}

export const componentRegistry: ComponentMeta[] = [

  {
    id: "Button",
    label: "Button",
    description: "Pressable button with variant and size support.",
    category: "action",
    tags: ["button", "cta", "action", "pressable"],
    themeMapping: { bg: "primary", text: "primaryForeground" },
    sizes: ["sm", "md", "lg"],
    variants: [
      {
        name: "primary",
        label: "Primary",
        overrides: { bg: undefined, color: undefined, borderWidth: 0 },
      },
      {
        name: "secondary",
        label: "Secondary",
        overrides: { bg: undefined, color: undefined, borderWidth: 0 },
      },
      {
        name: "outline",
        label: "Outline",
        overrides: { bg: "transparent", borderWidth: 1 },
      },
      {
        name: "ghost",
        label: "Ghost",
        overrides: { bg: "transparent", borderWidth: 0 },
      },
      {
        name: "destructive",
        label: "Destructive",
        overrides: { bg: undefined, color: undefined, borderWidth: 0 },
      },
    ],
    props: [
      { name: "label",         label: "Label",         type: "string",  group: "content",  default: "Button" },
      { name: "variant",      label: "Variant",       type: "enum",    group: "style",    default: "primary", options: ["primary", "secondary", "outline", "ghost", "destructive"] },
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "loading",       label: "Loading",       type: "boolean", group: "behavior", default: false },
      { name: "fullWidth",     label: "Full width",    type: "boolean", group: "layout",   default: false },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "md" },
      { name: "iconPosition",  label: "Icon position", type: "enum",    group: "layout",   default: "left", options: ["left", "right"] },
    ],
  },

  {
    id: "TextInput",
    label: "Text Input",
    description: "Single-line text input with label, error state, and icon support.",
    category: "input",
    tags: ["input", "text", "field", "form"],
    themeMapping: { bg: "input", text: "foreground", border: "border", placeholder: "mutedForeground" },
    sizes: ["sm", "md", "lg"],
    variants: [
      { name: "outlined", label: "Outlined", overrides: { borderWidth: 1, bg: "transparent" } },
      { name: "filled",   label: "Filled",   overrides: { borderWidth: 0 } },
      { name: "underline", label: "Underline", overrides: { borderWidth: 0, borderBottomWidth: 1, borderRadius: "none" } },
    ],
    props: [
      { name: "variant",       label: "Variant",        type: "enum",    group: "style",    default: "outlined", options: ["outlined", "filled", "underline"] },
      { name: "size",           label: "Size",           type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "placeholder",    label: "Placeholder",    type: "string",  group: "content" },
      { name: "label",          label: "Label",          type: "string",  group: "content" },
      { name: "error",          label: "Error message",  type: "string",  group: "content" },
      { name: "disabled",       label: "Disabled",       type: "boolean", group: "behavior", default: false },
      { name: "secureEntry",    label: "Password",       type: "boolean", group: "behavior", default: false },
      { name: "borderRadius",   label: "Border radius",  type: "radius",  group: "style",    default: "md" },
      { name: "background",     label: "Background",     type: "color",   group: "style",    themeDefault: "input" },
      { name: "borderColor",    label: "Border color",   type: "color",   group: "style",    themeDefault: "border" },
    ],
  },

  {
    id: "TextArea",
    label: "Text Area",
    description: "Multi-line text input.",
    category: "input",
    tags: ["textarea", "multiline", "input", "form"],
    themeMapping: { bg: "input", text: "foreground", border: "border" },
    sizes: ["sm", "md", "lg"],
    variants: [
      { name: "outlined", label: "Outlined", overrides: { borderWidth: 1, bg: "transparent" } },
      { name: "filled",   label: "Filled",   overrides: { borderWidth: 0 } },
    ],
    props: [
      { name: "variant",       label: "Variant",        type: "enum",    group: "style",    default: "outlined", options: ["outlined", "filled"] },
      { name: "size",           label: "Size",           type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "placeholder",    label: "Placeholder",    type: "string",  group: "content" },
      { name: "label",          label: "Label",          type: "string",  group: "content" },
      { name: "error",          label: "Error message",  type: "string",  group: "content" },
      { name: "disabled",       label: "Disabled",       type: "boolean", group: "behavior", default: false },
      { name: "numberOfLines",  label: "Lines",          type: "number",  group: "layout",   default: 4 },
      { name: "borderRadius",   label: "Border radius",  type: "radius",  group: "style",    default: "md" },
      { name: "background",     label: "Background",     type: "color",   group: "style",    themeDefault: "input" },
    ],
  },

  {
    id: "Checkbox",
    label: "Checkbox",
    description: "Toggle checkbox with label.",
    category: "input",
    tags: ["checkbox", "toggle", "form", "boolean"],
    themeMapping: { active: "primary", border: "border" },
    sizes: ["sm", "md"],
    variants: [
      { name: "square",  label: "Square",  overrides: { borderRadius: "sm" } },
      { name: "rounded", label: "Rounded", overrides: { borderRadius: "full" } },
    ],
    props: [
      { name: "variant",     label: "Variant",       type: "enum",    group: "style",    default: "square", options: ["square", "rounded"] },
      { name: "size",         label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md"] },
      { name: "disabled",     label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "label",        label: "Label",         type: "string",  group: "content" },
      { name: "activeColor",  label: "Active color",  type: "color",   group: "style",    themeDefault: "primary" },
    ],
  },

  {
    id: "Switch",
    label: "Switch",
    description: "Toggle switch.",
    category: "input",
    tags: ["switch", "toggle", "boolean"],
    themeMapping: { active: "primary", track: "muted" },
    sizes: ["sm", "md"],
    variants: [],
    props: [
      { name: "size",         label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md"] },
      { name: "disabled",     label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "label",        label: "Label",         type: "string",  group: "content" },
      { name: "activeColor",  label: "Active color",  type: "color",   group: "style",    themeDefault: "primary" },
      { name: "trackColor",   label: "Track color",   type: "color",   group: "style",    themeDefault: "muted" },
    ],
  },

  {
    id: "Badge",
    label: "Badge",
    description: "Small status indicator or label.",
    category: "display",
    tags: ["badge", "tag", "label", "status"],
    themeMapping: { bg: "primary", text: "primaryForeground" },
    sizes: ["sm", "md"],
    variants: [
      { name: "solid",   label: "Solid",   overrides: {} },
      { name: "outline", label: "Outline", overrides: { bg: "transparent", borderWidth: 1 } },
      { name: "subtle",  label: "Subtle",  overrides: {} },
    ],
    props: [
      { name: "label",        label: "Label",         type: "string",  group: "content" },
      { name: "variant",      label: "Variant",       type: "enum",    group: "style",    default: "solid", options: ["solid", "outline", "subtle"] },
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md"] },
      { name: "color",         label: "Color scheme",  type: "enum",    group: "style",    default: "primary", options: ["primary", "secondary", "success", "warning", "error", "info"] },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "full" },
    ],
  },

  {
    id: "Avatar",
    label: "Avatar",
    description: "User avatar with image, initials, or icon fallback.",
    category: "display",
    tags: ["avatar", "user", "profile", "image"],
    themeMapping: { bg: "muted", text: "mutedForeground" },
    sizes: ["xs", "sm", "md", "lg", "xl"],
    variants: [
      { name: "circle", label: "Circle", overrides: { borderRadius: "full" } },
      { name: "square", label: "Square", overrides: { borderRadius: "md" } },
    ],
    props: [
      { name: "variant",      label: "Shape",         type: "enum",    group: "style",    default: "circle", options: ["circle", "square"] },
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["xs", "sm", "md", "lg", "xl"] },
      { name: "source",        label: "Image source",  type: "string",  group: "content" },
      { name: "initials",      label: "Initials",      type: "string",  group: "content" },
      { name: "background",    label: "Background",    type: "color",   group: "style",    themeDefault: "muted" },
    ],
  },

  {
    id: "IconButton",
    label: "Icon Button",
    description: "Pressable icon-only button.",
    category: "action",
    tags: ["icon", "button", "action"],
    themeMapping: { bg: "muted", icon: "foreground" },
    sizes: ["sm", "md", "lg"],
    variants: [
      { name: "filled", label: "Filled", overrides: {} },
      { name: "ghost",  label: "Ghost",  overrides: { bg: "transparent" } },
      { name: "outline", label: "Outline", overrides: { bg: "transparent", borderWidth: 1 } },
    ],
    props: [
      { name: "variant",      label: "Variant",       type: "enum",    group: "style",    default: "ghost", options: ["filled", "ghost", "outline"] },
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "full" },
      { name: "color",         label: "Icon color",    type: "color",   group: "style",    themeDefault: "foreground" },
    ],
  },

  {
    id: "Chip",
    label: "Chip",
    description: "Selectable chip / tag with optional close action.",
    category: "input",
    tags: ["chip", "tag", "filter", "selectable"],
    themeMapping: { bg: "muted", text: "foreground", active: "primary" },
    sizes: ["sm", "md"],
    variants: [
      { name: "filled",  label: "Filled",  overrides: {} },
      { name: "outline", label: "Outline", overrides: { bg: "transparent", borderWidth: 1 } },
    ],
    props: [
      { name: "label",        label: "Label",         type: "string",  group: "content" },
      { name: "variant",      label: "Variant",       type: "enum",    group: "style",    default: "filled", options: ["filled", "outline"] },
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md"] },
      { name: "selected",      label: "Selected",      type: "boolean", group: "behavior", default: false },
      { name: "closable",      label: "Closable",      type: "boolean", group: "behavior", default: false },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "full" },
    ],
  },

  {
    id: "Spinner",
    label: "Spinner",
    description: "Loading indicator.",
    category: "feedback",
    tags: ["spinner", "loading", "indicator"],
    themeMapping: { color: "primary" },
    sizes: ["sm", "md", "lg"],
    variants: [],
    props: [
      { name: "size",   label: "Size",  type: "enum",  group: "style", default: "md", options: ["sm", "md", "lg"] },
      { name: "color",  label: "Color", type: "color", group: "style", themeDefault: "primary" },
    ],
  },

  {
    id: "Select",
    label: "Select",
    description: "Dropdown select input with options.",
    category: "input",
    tags: ["select", "dropdown", "picker", "form"],
    themeMapping: { bg: "input", text: "foreground", border: "border" },
    sizes: ["sm", "md", "lg"],
    variants: [
      { name: "outlined", label: "Outlined", overrides: { borderWidth: 1 } },
      { name: "filled",   label: "Filled",   overrides: { borderWidth: 0 } },
    ],
    props: [
      { name: "variant",      label: "Variant",       type: "enum",    group: "style",    default: "outlined", options: ["outlined", "filled"] },
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "label",         label: "Label",         type: "string",  group: "content" },
      { name: "placeholder",   label: "Placeholder",   type: "string",  group: "content",  default: "Select..." },
      { name: "error",         label: "Error message",  type: "string",  group: "content" },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "md" },
      { name: "background",    label: "Background",    type: "color",   group: "style",    themeDefault: "input" },
    ],
  },

  {
    id: "RadioGroup",
    label: "Radio Group",
    description: "Group of radio buttons for single selection.",
    category: "input",
    tags: ["radio", "group", "select", "form"],
    themeMapping: { active: "primary", border: "border", text: "foreground" },
    sizes: ["sm", "md"],
    variants: [],
    props: [
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md"] },
      { name: "label",         label: "Label",         type: "string",  group: "content" },
      { name: "direction",     label: "Direction",     type: "enum",    group: "layout",   default: "column", options: ["column", "row"] },
      { name: "spacing",       label: "Spacing",       type: "spacing", group: "layout",   default: 2 },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "activeColor",   label: "Active color",  type: "color",   group: "style",    themeDefault: "primary" },
    ],
  },

  {
    id: "DatePicker",
    label: "Date Picker",
    description: "Date/time picker input.",
    category: "input",
    tags: ["date", "time", "picker", "calendar", "form"],
    themeMapping: { bg: "input", text: "foreground", border: "border", accent: "primary" },
    sizes: ["sm", "md", "lg"],
    variants: [],
    props: [
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "mode",          label: "Mode",          type: "enum",    group: "behavior", default: "date", options: ["date", "time", "datetime"] },
      { name: "label",         label: "Label",         type: "string",  group: "content" },
      { name: "placeholder",   label: "Placeholder",   type: "string",  group: "content",  default: "Select date" },
      { name: "error",         label: "Error message",  type: "string",  group: "content" },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "md" },
    ],
  },

  {
    id: "FilePicker",
    label: "File Picker",
    description: "File/image upload input.",
    category: "input",
    tags: ["file", "upload", "image", "picker", "form"],
    themeMapping: { bg: "muted", text: "foreground", border: "border", accent: "primary" },
    sizes: ["sm", "md", "lg"],
    variants: [
      { name: "button", label: "Button", overrides: {} },
      { name: "dropzone", label: "Drop Zone", overrides: {} },
    ],
    props: [
      { name: "variant",      label: "Variant",       type: "enum",    group: "style",    default: "button", options: ["button", "dropzone"] },
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg"] },
      { name: "accept",        label: "Accept types",  type: "string",  group: "behavior", default: "image/*" },
      { name: "multiple",      label: "Multiple",      type: "boolean", group: "behavior", default: false },
      { name: "label",         label: "Label",         type: "string",  group: "content",  default: "Upload file" },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "md" },
    ],
  },

  {
    id: "Slider",
    label: "Slider",
    description: "Range slider input.",
    category: "input",
    tags: ["slider", "range", "input", "form"],
    themeMapping: { active: "primary", track: "muted" },
    sizes: ["sm", "md"],
    variants: [],
    props: [
      { name: "size",          label: "Size",          type: "enum",    group: "style",    default: "md", options: ["sm", "md"] },
      { name: "min",           label: "Min",           type: "number",  group: "behavior", default: 0 },
      { name: "max",           label: "Max",           type: "number",  group: "behavior", default: 100 },
      { name: "step",          label: "Step",          type: "number",  group: "behavior", default: 1 },
      { name: "label",         label: "Label",         type: "string",  group: "content" },
      { name: "showValue",     label: "Show value",    type: "boolean", group: "behavior", default: true },
      { name: "disabled",      label: "Disabled",      type: "boolean", group: "behavior", default: false },
      { name: "activeColor",   label: "Active color",  type: "color",   group: "style",    themeDefault: "primary" },
    ],
  },

  {
    id: "Image",
    label: "Image",
    description: "Image component with source, resize mode, and placeholder.",
    category: "display",
    tags: ["image", "photo", "picture", "media"],
    themeMapping: { bg: "muted" },
    sizes: [],
    variants: [],
    props: [
      { name: "source",       label: "Source URL",     type: "string",  group: "content" },
      { name: "alt",           label: "Alt text",      type: "string",  group: "content" },
      { name: "resizeMode",    label: "Resize mode",   type: "enum",    group: "style",    default: "cover", options: ["cover", "contain", "stretch", "center"] },
      { name: "width",         label: "Width",         type: "number",  group: "layout" },
      { name: "height",        label: "Height",        type: "number",  group: "layout",   default: 200 },
      { name: "borderRadius",  label: "Border radius", type: "radius",  group: "style",    default: "none" },
      { name: "background",    label: "Placeholder bg", type: "color",  group: "style",    themeDefault: "muted" },
    ],
  },

  {
    id: "Icon",
    label: "Icon",
    description: "Vector icon from Feather icon set.",
    category: "display",
    tags: ["icon", "feather", "vector", "symbol"],
    themeMapping: { color: "foreground" },
    sizes: ["sm", "md", "lg"],
    variants: [],
    props: [
      { name: "name",   label: "Icon name",  type: "string",  group: "content",  default: "star" },
      { name: "size",   label: "Size",       type: "number",  group: "style",    default: 24 },
      { name: "color",  label: "Color",      type: "color",   group: "style",    themeDefault: "foreground" },
    ],
  },

  {
    id: "Gradient",
    label: "Gradient",
    description: "Linear gradient background container.",
    category: "display",
    tags: ["gradient", "linear", "background", "color"],
    themeMapping: {},
    sizes: [],
    variants: [],
    props: [
      { name: "startColor",  label: "Start color",  type: "color",   group: "style",    default: "#3b82f6" },
      { name: "endColor",    label: "End color",    type: "color",   group: "style",    default: "#8b5cf6" },
      { name: "direction",   label: "Direction",    type: "enum",    group: "style",    default: "vertical", options: ["vertical", "horizontal", "diagonal"] },
      { name: "borderRadius", label: "Border radius", type: "radius", group: "style",   default: "none" },
      { name: "height",      label: "Height",       type: "number",  group: "layout" },
      { name: "padding",     label: "Padding",      type: "spacing", group: "layout" },
    ],
  },

  {
    id: "Separator",
    label: "Separator",
    description: "Visual separator with optional label.",
    category: "display",
    tags: ["separator", "divider", "or", "line"],
    themeMapping: { color: "border", text: "mutedForeground" },
    sizes: [],
    variants: [],
    props: [
      { name: "label",     label: "Label",     type: "string",  group: "content" },
      { name: "color",     label: "Color",     type: "color",   group: "style",    themeDefault: "border" },
      { name: "thickness", label: "Thickness", type: "number",  group: "style",    default: 1 },
      { name: "spacing",   label: "Spacing",   type: "spacing", group: "layout",   default: 4 },
    ],
  },

  {
    id: "Text",
    label: "Text",
    description: "Text display component with typography control.",
    category: "display",
    tags: ["text", "label", "paragraph", "heading", "typography"],
    themeMapping: { color: "foreground" },
    sizes: [],
    variants: [],
    props: [
      { name: "text",          label: "Text",          type: "string",  group: "content",  default: "Text" },
      { name: "fontSize",      label: "Font size",     type: "number",  group: "style",    default: 14 },
      { name: "fontWeight",    label: "Font weight",   type: "enum",    group: "style",    default: "400", options: ["300", "400", "500", "600", "700", "800"] },
      { name: "color",         label: "Color",         type: "color",   group: "style",    themeDefault: "foreground" },
      { name: "textAlign",     label: "Align",         type: "enum",    group: "style",    default: "left", options: ["left", "center", "right"] },
      { name: "numberOfLines", label: "Max lines",     type: "number",  group: "behavior" },
    ],
  },

  {
    id: "Video",
    label: "Video",
    description: "Video player with controls, autoplay, and loop.",
    category: "media",
    tags: ["video", "player", "media", "stream"],
    themeMapping: { bg: "muted" },
    sizes: [],
    variants: [],
    props: [
      { name: "source",       label: "Source URL",     type: "string",  group: "content" },
      { name: "poster",       label: "Poster URL",     type: "string",  group: "content" },
      { name: "autoplay",     label: "Autoplay",       type: "boolean", group: "behavior", default: false },
      { name: "loop",         label: "Loop",           type: "boolean", group: "behavior", default: false },
      { name: "muted",        label: "Muted",          type: "boolean", group: "behavior", default: true },
      { name: "controls",     label: "Show controls",  type: "boolean", group: "behavior", default: true },
      { name: "resizeMode",   label: "Resize mode",    type: "enum",    group: "style",    default: "contain", options: ["cover", "contain", "stretch"] },
      { name: "width",        label: "Width",          type: "number",  group: "layout" },
      { name: "height",       label: "Height",         type: "number",  group: "layout",   default: 220 },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "none" },
    ],
  },

  {
    id: "Camera",
    label: "Camera",
    description: "Camera viewfinder for photo/video capture.",
    category: "media",
    tags: ["camera", "photo", "capture", "scan"],
    themeMapping: { bg: "muted" },
    sizes: [],
    variants: [],
    props: [
      { name: "facing",       label: "Facing",         type: "enum",    group: "behavior", default: "back", options: ["front", "back"] },
      { name: "flash",        label: "Flash",          type: "enum",    group: "behavior", default: "off", options: ["off", "on", "auto"] },
      { name: "enableTorch",  label: "Torch",          type: "boolean", group: "behavior", default: false },
      { name: "width",        label: "Width",          type: "number",  group: "layout" },
      { name: "height",       label: "Height",         type: "number",  group: "layout",   default: 300 },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "lg" },
    ],
  },

  {
    id: "WebView",
    label: "WebView",
    description: "Embedded web browser view.",
    category: "media",
    tags: ["webview", "browser", "iframe", "embed"],
    themeMapping: { bg: "muted" },
    sizes: [],
    variants: [],
    props: [
      { name: "url",          label: "URL",            type: "string",  group: "content",  default: "https://expo.dev" },
      { name: "width",        label: "Width",          type: "number",  group: "layout" },
      { name: "height",       label: "Height",         type: "number",  group: "layout",   default: 400 },
      { name: "scrollEnabled", label: "Scroll",        type: "boolean", group: "behavior", default: true },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "none" },
    ],
  },

  {
    id: "MapView",
    label: "Map",
    description: "Interactive map view with markers.",
    category: "media",
    tags: ["map", "location", "gps", "marker"],
    themeMapping: {},
    sizes: [],
    variants: [],
    props: [
      { name: "latitude",     label: "Latitude",       type: "number",  group: "content",  default: 48.8566 },
      { name: "longitude",    label: "Longitude",      type: "number",  group: "content",  default: 2.3522 },
      { name: "zoom",         label: "Zoom",           type: "number",  group: "content",  default: 12 },
      { name: "width",        label: "Width",          type: "number",  group: "layout" },
      { name: "height",       label: "Height",         type: "number",  group: "layout",   default: 300 },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "lg" },
      { name: "showsUserLocation", label: "User location", type: "boolean", group: "behavior", default: true },
    ],
  },

  {
    id: "BlurView",
    label: "Blur View",
    description: "Blurred background overlay container.",
    category: "display",
    tags: ["blur", "glass", "frosted", "overlay"],
    themeMapping: {},
    sizes: [],
    variants: [],
    props: [
      { name: "intensity",    label: "Intensity",      type: "number",  group: "style",    default: 50 },
      { name: "tint",         label: "Tint",           type: "enum",    group: "style",    default: "default", options: ["default", "light", "dark"] },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "none" },
      { name: "padding",      label: "Padding",        type: "spacing", group: "layout" },
    ],
  },

  {
    id: "LottieAnimation",
    label: "Lottie",
    description: "Lottie animation player.",
    category: "media",
    tags: ["lottie", "animation", "motion", "json"],
    themeMapping: {},
    sizes: [],
    variants: [],
    props: [
      { name: "source",       label: "Source URL",     type: "string",  group: "content" },
      { name: "autoPlay",     label: "Auto play",      type: "boolean", group: "behavior", default: true },
      { name: "loop",         label: "Loop",           type: "boolean", group: "behavior", default: true },
      { name: "speed",        label: "Speed",          type: "number",  group: "behavior", default: 1 },
      { name: "width",        label: "Width",          type: "number",  group: "layout",   default: 200 },
      { name: "height",       label: "Height",         type: "number",  group: "layout",   default: 200 },
    ],
  },

  {
    id: "ProgressBar",
    label: "Progress Bar",
    description: "Horizontal progress indicator.",
    category: "feedback",
    tags: ["progress", "bar", "loading", "percentage"],
    themeMapping: { active: "primary", track: "muted" },
    sizes: ["sm", "md"],
    variants: [],
    props: [
      { name: "progress",     label: "Progress (0-1)", type: "number",  group: "content",  default: 0.5 },
      { name: "size",         label: "Size",           type: "enum",    group: "style",    default: "md", options: ["sm", "md"] },
      { name: "color",        label: "Color",          type: "color",   group: "style",    themeDefault: "primary" },
      { name: "trackColor",   label: "Track color",    type: "color",   group: "style",    themeDefault: "muted" },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "full" },
      { name: "showLabel",    label: "Show label",     type: "boolean", group: "behavior", default: false },
    ],
  },

  {
    id: "Accordion",
    label: "Accordion",
    description: "Expandable/collapsible content section.",
    category: "display",
    tags: ["accordion", "collapse", "expand", "faq"],
    themeMapping: { bg: "card", text: "foreground", border: "border" },
    sizes: [],
    variants: [],
    props: [
      { name: "title",        label: "Title",          type: "string",  group: "content",  default: "Section" },
      { name: "defaultOpen",  label: "Default open",   type: "boolean", group: "behavior", default: false },
      { name: "background",   label: "Background",     type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "lg" },
      { name: "borderColor",  label: "Border color",   type: "color",   group: "style",    themeDefault: "border" },
    ],
  },

  {
    id: "Tabs",
    label: "Tabs",
    description: "Tab navigation with content panels.",
    category: "navigation",
    tags: ["tabs", "navigation", "panel", "switch"],
    themeMapping: { active: "primary", bg: "card", border: "border" },
    sizes: [],
    variants: [],
    props: [
      { name: "activeColor",  label: "Active color",   type: "color",   group: "style",    themeDefault: "primary" },
      { name: "background",   label: "Background",     type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "none" },
      { name: "position",     label: "Position",       type: "enum",    group: "layout",   default: "top", options: ["top", "bottom"] },
    ],
  },

  {
    id: "Pressable",
    label: "Pressable",
    description: "Generic pressable wrapper with feedback.",
    category: "action",
    tags: ["pressable", "touchable", "tap", "click"],
    themeMapping: {},
    sizes: [],
    variants: [],
    props: [
      { name: "disabled",     label: "Disabled",       type: "boolean", group: "behavior", default: false },
      { name: "opacity",      label: "Press opacity",  type: "number",  group: "style",    default: 0.7 },
    ],
  },

  {
    id: "FlatList",
    label: "List",
    description: "Scrollable list with virtualization.",
    category: "display",
    tags: ["list", "flatlist", "scroll", "virtualized"],
    themeMapping: { bg: "background" },
    sizes: [],
    variants: [],
    props: [
      { name: "horizontal",   label: "Horizontal",     type: "boolean", group: "layout",   default: false },
      { name: "numColumns",   label: "Columns",        type: "number",  group: "layout",   default: 1 },
      { name: "spacing",      label: "Item spacing",   type: "spacing", group: "layout",   default: 0 },
      { name: "showsScrollIndicator", label: "Scroll indicator", type: "boolean", group: "behavior", default: true },
      { name: "background",   label: "Background",     type: "color",   group: "style" },
    ],
  },
];
