/**
 * Layout Registry — Définitions complètes
 *
 * Chaque layout est décrit avec ses slots, props configurables,
 * valeurs par défaut, types, groupes et contraintes.
 */

import type { LayoutMeta } from "../types";

// ─── Helper pour lookup rapide ────────────────────────────────────────────────

export function getLayoutMeta(id: string): LayoutMeta | undefined {
  return layoutRegistry.find((m) => m.id === id);
}

// ─── Registre ─────────────────────────────────────────────────────────────────

export const layoutRegistry: LayoutMeta[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "RootLayout",
    label: "Root",
    description: "Root page container with direct flex control. Ideal as the base of every page.",
    category: "page",
    slots: [{ name: "children", label: "Content", required: true, kind: "children" }],
    responsive: false,
    animated: false,
    tags: ["root", "page", "container", "flex"],
    themeMapping: { root: "background" },
    props: [
      { name: "background",     label: "Background",     type: "color",   group: "style",    themeDefault: "background" },
      { name: "scrollable",     label: "Scrollable",     type: "boolean", group: "behavior", default: true },
      { name: "padding",        label: "Padding",        type: "spacing", group: "layout",   default: 0 },
      { name: "justifyContent", label: "Justify",        type: "enum",    group: "layout",   default: "flex-start", options: ["flex-start", "center", "flex-end", "space-between", "space-around", "space-evenly"] },
      { name: "alignItems",     label: "Align Items",    type: "enum",    group: "layout",   default: "stretch", options: ["stretch", "flex-start", "center", "flex-end", "baseline"] },
      { name: "flexDirection",  label: "Direction",      type: "enum",    group: "layout",   default: "column", options: ["column", "row"] },
      { name: "gap",            label: "Gap",            type: "number",  group: "layout",   default: 0 },
    ],
  },

  {
    id: "VoidLayout",
    label: "Vide",
    description: "Conteneur minimal avec scroll, padding et maxWidth optionnels.",
    category: "page",
    slots: [{ name: "children", label: "Contenu", required: true, kind: "children" }],
    responsive: false,
    animated: false,
    tags: ["blank", "empty", "minimal", "wrapper"],
    props: [
      { name: "maxWidth",      label: "Largeur max",     type: "number",  group: "layout",   description: "Largeur maximale du conteneur" },
      { name: "scrollable",    label: "Scrollable",      type: "boolean", group: "behavior", default: true },
      { name: "background",    label: "Fond",            type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",  label: "Rayon bordure",   type: "radius",  group: "style",    default: "none" },
      { name: "padding",       label: "Padding",         type: "padding", group: "layout" },
      { name: "spacing",       label: "Espacement",      type: "spacing", group: "layout",   default: 0 },
      { name: "centerContent", label: "Centrer contenu", type: "boolean", group: "layout",   default: false },
      { name: "showBorder",    label: "Bordure visible", type: "boolean", group: "style",    default: false },
    ],
  },

  {
    id: "CenteredLayout",
    label: "Centré",
    description: "Contenu centré avec carte optionnelle et maxWidth.",
    category: "page",
    slots: [{ name: "children", label: "Contenu", required: true, kind: "children" }],
    responsive: true,
    animated: false,
    tags: ["centered", "form", "onboarding", "modal"],
    themeMapping: { root: "background", surface: "card" },
    props: [
      { name: "maxWidth",        label: "Largeur max carte", type: "number",  group: "layout",   default: 500 },
      { name: "padding",         label: "Padding carte",     type: "spacing", group: "layout",   default: 4 },
      { name: "background",      label: "Fond page",         type: "color",   group: "style",    themeDefault: "background" },
      { name: "cardBackground",  label: "Fond carte",        type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius",    label: "Rayon bordure",     type: "radius",  group: "style",    default: "3xl" },
      { name: "shadowed",        label: "Ombre carte",       type: "boolean", group: "style",    default: false },
      { name: "mobilePadding",   label: "Padding mobile",    type: "spacing", group: "layout",   default: 4 },
      { name: "desktopPadding",  label: "Padding desktop",   type: "spacing", group: "layout",   default: 6 },
    ],
  },

  {
    id: "AuthLayout",
    label: "Authentification",
    description: "Panel branding (desktop) + formulaire centré. Mobile : plein écran.",
    category: "page",
    themeMapping: { root: "background", surface: "card" },
    slots: [
      { name: "children", label: "Formulaire",     required: true,  kind: "children" },
      { name: "branding", label: "Panel branding", required: false, kind: "named" },
    ],
    responsive: true,
    animated: false,
    tags: ["auth", "login", "signup", "onboarding"],
    props: [
      { name: "brandingBackground",  label: "Fond branding",         type: "color",   group: "style",    themeDefault: "card" },
      { name: "background",          label: "Fond",                  type: "background", group: "style" },
      { name: "borderRadius",        label: "Rayon bordure",         type: "radius",  group: "style",    default: "none" },
      { name: "spacing",             label: "Espacement",            type: "spacing", group: "layout",   default: 0 },
      { name: "brandingRatio",       label: "Ratio branding",        type: "ratio",   group: "layout",   default: 0.5, min: 0, max: 1 },
      { name: "padding",             label: "Padding formulaire",    type: "spacing", group: "layout",   default: 5 },
      { name: "shadowed",            label: "Ombre mobile",          type: "boolean", group: "style",    default: true },
      { name: "formMaxWidth",        label: "Largeur max formulaire", type: "number",  group: "layout",   default: 520 },
      { name: "formScrollPaddingY",  label: "Padding scroll Y",      type: "spacing", group: "layout",   default: 8 },
      { name: "formScrollPaddingX",  label: "Padding scroll X",      type: "spacing", group: "layout",   default: 4 },
    ],
  },

  {
    id: "DashboardLayout",
    label: "Dashboard",
    description: "Header fixe, sidebar collapsible, contenu scrollable, footer optionnel.",
    category: "page",
    themeMapping: { root: "background", surface: "card" },
    slots: [
      { name: "header",  label: "Header",  required: true,  kind: "named" },
      { name: "content", label: "Contenu", required: true,  kind: "named" },
      { name: "sidebar", label: "Sidebar", required: false, kind: "named" },
      { name: "footer",  label: "Footer",  required: false, kind: "named" },
    ],
    responsive: true,
    animated: true,
    dependencies: ["react-native-reanimated"],
    tags: ["dashboard", "admin", "sidebar", "header"],
    props: [
      { name: "sidebarWidth",          label: "Largeur sidebar",          type: "number",  group: "layout",   default: 260 },
      { name: "sidebarCollapsedWidth",  label: "Largeur sidebar réduite", type: "number",  group: "layout",   default: 70 },
      { name: "headerHeight",          label: "Hauteur header",           type: "number",  group: "layout",   default: 70 },
      { name: "footerHeight",          label: "Hauteur footer",           type: "number",  group: "layout",   default: 60 },
      { name: "spacing",               label: "Espacement",               type: "spacing", group: "layout",   default: 0 },
      { name: "borderRadius",          label: "Rayon bordure",            type: "radius",  group: "style",    default: "none" },
      { name: "background",            label: "Fond",                     type: "color",   group: "style",    themeDefault: "background" },
      { name: "disableContentScroll",  label: "Désactiver scroll contenu", type: "boolean", group: "behavior", default: false },
      { name: "headerBackground",      label: "Fond header",               type: "color",   group: "style",    themeDefault: "card" },
      { name: "sidebarBackground",     label: "Fond sidebar",              type: "color",   group: "style",    themeDefault: "card" },
      { name: "contentBackground",     label: "Fond contenu",              type: "color",   group: "style",    themeDefault: "card" },
      { name: "footerBackground",      label: "Fond footer",               type: "color",   group: "style",    themeDefault: "card" },
      { name: "headerPaddingX",        label: "Padding X header",          type: "spacing", group: "layout",   default: 4 },
      { name: "mobileHeaderMinHeight", label: "Hauteur min header mobile", type: "number",  group: "layout",   default: 60 },
    ],
  },

  {
    id: "ResponsiveLayout",
    label: "Responsive",
    description: "Layout adaptatif header/sidebar/content/footer avec 3 modes.",
    category: "page",
    themeMapping: { root: "background" },
    slots: [
      { name: "content", label: "Contenu",  required: true,  kind: "named" },
      { name: "header",  label: "Header",   required: false, kind: "named" },
      { name: "sidebar", label: "Sidebar",  required: false, kind: "named" },
      { name: "footer",  label: "Footer",   required: false, kind: "named" },
    ],
    responsive: true,
    animated: false,
    tags: ["responsive", "adaptive", "header", "sidebar", "footer"],
    props: [
      { name: "spacing",                label: "Espacement",              type: "spacing", group: "layout",   default: 0 },
      { name: "headerHeight",           label: "Hauteur header",          type: "number",  group: "layout",   default: 60 },
      { name: "sidebarWidth",           label: "Largeur sidebar",         type: "number",  group: "layout",   default: 260 },
      { name: "footerHeight",           label: "Hauteur footer",          type: "number",  group: "layout",   default: 60 },
      { name: "adaptiveMode",           label: "Mode adaptatif",          type: "enum",    group: "behavior", default: "basic", options: ["basic", "sidebar", "full"] },
      { name: "hideHeader",             label: "Cacher header",           type: "boolean", group: "behavior", default: false },
      { name: "hideFooter",             label: "Cacher footer",           type: "boolean", group: "behavior", default: false },
      { name: "collapseFooterOnTablet", label: "Footer compact tablette", type: "boolean", group: "behavior", default: false },
      { name: "background",             label: "Fond",                    type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",           label: "Rayon bordure",           type: "radius",  group: "style",    default: "none" },
      { name: "headerBackground",       label: "Fond header",             type: "color",   group: "style",    themeDefault: "background" },
      { name: "sidebarBackground",      label: "Fond sidebar",            type: "color",   group: "style",    themeDefault: "background" },
      { name: "footerBackground",       label: "Fond footer",             type: "color",   group: "style",    themeDefault: "background" },
      { name: "contentBackground",      label: "Fond contenu",            type: "color",   group: "style" },
      { name: "padding",                label: "Padding",                 type: "padding", group: "layout" },
      { name: "contentPadding",         label: "Padding contenu",         type: "padding", group: "layout" },
      { name: "mobileHeaderHeight",     label: "Hauteur header mobile",   type: "number",  group: "layout",   default: 56 },
      { name: "tabletFooterHeight",     label: "Hauteur footer tablette", type: "number",  group: "layout",   default: 48 },
      { name: "sidebarMaxWidth",        label: "Largeur max sidebar",     type: "number",  group: "layout",   default: 320 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONTENT
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "FlexLayout",
    label: "Flex",
    description: "Direction, wrap et espacement adaptatifs. Scroll optionnel.",
    category: "content",
    themeMapping: { root: "background" },
    slots: [{ name: "children", label: "Éléments", required: true, kind: "children" }],
    responsive: true,
    animated: false,
    tags: ["flex", "row", "column", "wrap", "adaptive"],
    props: [
      { name: "direction",    label: "Direction",       type: "enum",    group: "layout",   default: "row", options: ["row", "column"] },
      { name: "wrap",         label: "Retour à la ligne", type: "boolean", group: "layout", default: false },
      { name: "spacing",      label: "Espacement",      type: "spacing", group: "layout",   default: 4 },
      { name: "align",        label: "Align Items",     type: "enum",    group: "layout",   default: "stretch", options: ["stretch", "flex-start", "center", "flex-end", "baseline"] },
      { name: "justify",      label: "Justify Content", type: "enum",    group: "layout",   default: "flex-start", options: ["flex-start", "center", "flex-end", "space-between", "space-around", "space-evenly"] },
      { name: "maxWidth",     label: "Largeur max",     type: "number",  group: "layout" },
      { name: "scrollable",   label: "Scrollable",      type: "boolean", group: "behavior", default: false },
      { name: "padding",      label: "Padding",         type: "padding", group: "layout" },
      { name: "background",   label: "Fond",            type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius", label: "Rayon bordure",   type: "radius",  group: "style",    default: "none" },
    ],
  },

  {
    id: "GridLayout",
    label: "Grille",
    description: "Grille responsive avec colonnes adaptatives.",
    category: "content",
    themeMapping: { root: "background", surface: "card" },
    slots: [{ name: "items", label: "Cellules", required: true, kind: "items" }],
    responsive: true,
    animated: false,
    previewItemCount: 6,
    tags: ["grid", "columns", "responsive"],
    props: [
      { name: "columns",          label: "Colonnes",          type: "number",  group: "layout",   description: "Nombre de colonnes (auto si omis)" },
      { name: "cellHeight",       label: "Hauteur cellule",   type: "number",  group: "layout",   description: "Hauteur fixe en px — omis = adaptatif au contenu" },
      { name: "spacing",          label: "Espacement",        type: "spacing", group: "layout",   default: 0 },
      { name: "maxWidth",         label: "Largeur max",       type: "number",  group: "layout" },
      { name: "scrollable",       label: "Scrollable",        type: "boolean", group: "behavior", default: false },
      { name: "padding",          label: "Padding",           type: "spacing", group: "layout",   default: 0 },
      { name: "itemBackground",   label: "Fond items",        type: "color",   group: "style",    themeDefault: "card" },
      { name: "itemBorderRadius", label: "Rayon items",       type: "radius",  group: "style",    default: "none" },
      { name: "background",       label: "Fond",              type: "color",   group: "style",    default: "transparent" },
      { name: "borderRadius",     label: "Rayon bordure",     type: "radius",  group: "style",    default: "none" },
      { name: "compact",          label: "Mode compact",      type: "boolean", group: "behavior", default: false },
    ],
  },

  {
    id: "BentoLayout",
    label: "Bento",
    description: "Grille bento box avec cellules de tailles variées.",
    category: "content",
    themeMapping: { root: "background" },
    slots: [{ name: "items", label: "Items", required: true, kind: "items" }],
    responsive: true,
    animated: false,
    previewItemCount: 5,
    tags: ["bento", "grid", "mosaic", "dashboard"],
    props: [
      { name: "spacing",          label: "Espacement",      type: "spacing", group: "layout",   default: 2 },
      { name: "itemBackground",   label: "Fond items",      type: "color",   group: "style",    themeDefault: "card" },
      { name: "itemBorderRadius", label: "Rayon items",     type: "radius",  group: "style",    default: "none" },
      { name: "scrollable",       label: "Scrollable",      type: "boolean", group: "behavior", default: true },
      { name: "maxWidth",         label: "Largeur max",     type: "number",  group: "layout",   default: 1200 },
      { name: "baseHeight",       label: "Hauteur de base", type: "number",  group: "layout",   default: 200 },
      { name: "background",       label: "Fond",            type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",     label: "Rayon bordure",   type: "radius",  group: "style",    default: "none" },
      { name: "cellConfig",       label: "Config cellules", type: "json",    group: "content",  default: [] },
    ],
  },

  {
    id: "MasonryLayout",
    label: "Masonry",
    description: "Grille masonry multi-colonnes.",
    category: "content",
    themeMapping: { root: "background", surface: "card" },
    slots: [{ name: "items", label: "Items", required: true, kind: "items" }],
    responsive: false,
    animated: false,
    previewItemCount: 6,
    tags: ["masonry", "pinterest", "waterfall"],
    props: [
      { name: "columns",          label: "Colonnes",      type: "number",  group: "layout",   default: 2 },
      { name: "spacing",          label: "Espacement",    type: "spacing", group: "layout",   default: 1 },
      { name: "maxWidth",         label: "Largeur max",   type: "number",  group: "layout" },
      { name: "scrollable",       label: "Scrollable",    type: "boolean", group: "behavior", default: true },
      { name: "background",       label: "Fond",          type: "color",   group: "style",    default: "transparent" },
      { name: "borderRadius",     label: "Rayon bordure", type: "radius",  group: "style",    default: "none" },
      { name: "itemBackground",   label: "Fond items",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "itemBorderRadius", label: "Rayon items",   type: "radius",  group: "style",    default: "none" },
      { name: "padding",          label: "Padding",       type: "padding", group: "layout" },
    ],
  },

  {
    id: "SplitLayout",
    label: "Split",
    description: "Deux panneaux (gauche/droite ou haut/bas) avec scroll indépendant.",
    category: "content",
    themeMapping: { root: "background", left: "card", right: "card" },
    slots: [
      { name: "left",  label: "Panneau gauche", required: true,  kind: "named" },
      { name: "right", label: "Panneau droit",  required: true,  kind: "named" },
    ],
    responsive: true,
    animated: false,
    tags: ["split", "two-pane", "master-detail"],
    props: [
      { name: "spacing",           label: "Espacement",          type: "spacing", group: "layout",   default: 0 },
      { name: "leftWidth",         label: "Largeur gauche fixe", type: "number",  group: "layout" },
      { name: "ratio",             label: "Ratio gauche",        type: "ratio",   group: "layout",   default: 0.5, min: 0, max: 1 },
      { name: "orientation",       label: "Orientation",         type: "enum",    group: "layout",   default: "horizontal", options: ["horizontal", "vertical"] },
      { name: "hideLeftOnMobile",  label: "Cacher gauche mobile", type: "boolean", group: "behavior", default: false },
      { name: "background",        label: "Fond",                type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",      label: "Rayon bordure",       type: "radius",  group: "style",    default: "none" },
      { name: "leftBackground",    label: "Fond gauche",         type: "color",   group: "style",    themeDefault: "card" },
      { name: "rightBackground",   label: "Fond droit",          type: "color",   group: "style",    themeDefault: "card" },
      { name: "leftBorderRadius",  label: "Rayon gauche",        type: "radius",  group: "style",    default: "none" },
      { name: "rightBorderRadius", label: "Rayon droit",         type: "radius",  group: "style",    default: "none" },
    ],
  },

  {
    id: "FooterLayout",
    label: "Footer",
    description: "Contenu principal avec footer fixe ou scrollable.",
    category: "content",
    themeMapping: { root: "background" },
    slots: [
      { name: "content", label: "Contenu", required: true,  kind: "named" },
      { name: "footer",  label: "Footer",  required: true,  kind: "named" },
    ],
    responsive: false,
    animated: false,
    tags: ["footer", "sticky", "bottom-bar"],
    props: [
      { name: "footerHeight",       label: "Hauteur footer",     type: "number",  group: "layout",   default: 60 },
      { name: "spacing",            label: "Espacement",         type: "spacing", group: "layout",   default: 0 },
      { name: "sticky",             label: "Footer sticky",      type: "boolean", group: "behavior", default: false },
      { name: "maxWidth",           label: "Largeur max",        type: "number",  group: "layout" },
      { name: "scrollable",         label: "Scrollable",         type: "boolean", group: "behavior", default: true },
      { name: "footerBackground",   label: "Fond footer",        type: "color",   group: "style",    themeDefault: "background" },
      { name: "footerBorderRadius", label: "Rayon footer",       type: "radius",  group: "style",    default: "none" },
      { name: "contentBorderRadius", label: "Rayon contenu",     type: "radius",  group: "style",    default: "none" },
      { name: "background",         label: "Fond",               type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",       label: "Rayon bordure",      type: "radius",  group: "style",    default: "none" },
      { name: "padding",            label: "Padding contenu",    type: "spacing", group: "layout",   default: 5 },
      { name: "footerPadding",      label: "Padding footer",     type: "spacing", group: "layout",   default: 5 },
      { name: "compact",            label: "Mode compact",       type: "boolean", group: "behavior", default: false },
    ],
  },

  {
    id: "CrossTabLayout",
    label: "Cross Tab",
    description: "Grille réordonnnable par drag & drop.",
    category: "content",
    themeMapping: { surface: "card" },
    constants: {
      springConfig: { damping: 18, stiffness: 120, mass: 0.5 },
    },
    slots: [{ name: "items", label: "Widgets", required: true, kind: "items" }],
    responsive: false,
    animated: true,
    previewItemCount: 4,
    dependencies: ["react-native-reanimated", "react-native-gesture-handler", "expo-haptics"],
    tags: ["drag", "drop", "reorder", "widgets", "grid"],
    props: [
      { name: "columns",          label: "Colonnes",      type: "number",  group: "layout",   default: 2 },
      { name: "spacing",          label: "Espacement",    type: "spacing", group: "layout",   default: 4 },
      { name: "itemBackground",   label: "Fond items",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "itemBorderRadius", label: "Rayon items",   type: "number",  group: "style",    default: 28 },
      { name: "scrollEnabled",    label: "Scroll activé", type: "boolean", group: "behavior", default: true },
      { name: "springDamping",    label: "Amortissement spring", type: "number", group: "behavior", default: 18 },
      { name: "springStiffness",  label: "Raideur spring",       type: "number", group: "behavior", default: 120 },
      { name: "longPressDuration", label: "Durée long-press",    type: "number", group: "behavior", default: 250 },
      { name: "dragScale",        label: "Échelle drag",         type: "ratio",  group: "behavior", default: 1.05, min: 1, max: 1.5 },
      { name: "background",       label: "Fond",                 type: "color",  group: "style",    themeDefault: "background" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NAVIGATION
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "SidebarLayout",
    label: "Sidebar",
    description: "Contenu avec sidebar latérale, collapsible sur mobile.",
    category: "navigation",
    themeMapping: { root: "background", sidebar: "card", border: "border" },
    slots: [
      { name: "sidebar", label: "Sidebar", required: true,  kind: "named" },
      { name: "content", label: "Contenu", required: true,  kind: "named" },
    ],
    responsive: true,
    animated: false,
    tags: ["sidebar", "navigation", "menu", "resizable"],
    props: [
      { name: "sidebarWidth",        label: "Largeur sidebar",   type: "number",  group: "layout",   default: 280 },
      { name: "position",            label: "Position sidebar",  type: "enum",    group: "layout",   default: "left", options: ["left", "right"] },
      { name: "collapsible",         label: "Collapsible mobile", type: "boolean", group: "behavior", default: true },
      { name: "spacing",             label: "Espacement",        type: "spacing", group: "layout",   default: 4 },
      { name: "maxWidth",            label: "Largeur max",       type: "number",  group: "layout" },
      { name: "scrollable",          label: "Scrollable",        type: "boolean", group: "behavior", default: true },
      { name: "background",          label: "Fond",              type: "background", group: "style" },
      { name: "borderRadius",        label: "Rayon bordure",     type: "radius",  group: "style",    default: "none" },
      { name: "sidebarBackground",   label: "Fond sidebar",      type: "background", group: "style" },
      { name: "sidebarBorderRadius", label: "Rayon sidebar",     type: "radius",  group: "style",    default: "none" },
      { name: "padding",             label: "Padding",           type: "padding", group: "layout" },
      { name: "resizable",           label: "Redimensionnable",  type: "boolean", group: "behavior", default: false },
      { name: "sidebarMinWidth",     label: "Largeur min sidebar", type: "number", group: "layout",   default: 150 },
      { name: "sidebarMaxWidth",     label: "Largeur max sidebar", type: "number", group: "layout",   default: 600 },
    ],
  },

  {
    id: "BottomDrawerLayout",
    label: "Tiroir bas",
    description: "Tiroir inférieur animé avec geste de swipe.",
    category: "navigation",
    themeMapping: { root: "background", drawer: "background", accent: "primary", border: "border" },
    constants: {
      springConfig: { damping: 25, stiffness: 200, mass: 0.5, overshootClamping: true },
    },
    slots: [
      { name: "content",       label: "Contenu principal",  required: true,  kind: "named" },
      { name: "drawerContent", label: "Contenu du tiroir",  required: true,  kind: "named" },
    ],
    responsive: true,
    animated: true,
    dependencies: ["react-native-reanimated", "react-native-gesture-handler", "expo-haptics"],
    tags: ["drawer", "bottom-sheet", "swipe", "modal"],
    props: [
      { name: "drawerHeight",       label: "Hauteur tiroir",  type: "number",  group: "layout",   default: 400 },
      { name: "maxWidth",           label: "Largeur max",     type: "number",  group: "layout" },
      { name: "scrollable",         label: "Scrollable",      type: "boolean", group: "behavior", default: true },
      { name: "drawerBackground",   label: "Fond tiroir",     type: "color",   group: "style",    themeDefault: "background" },
      { name: "drawerBorderRadius", label: "Rayon tiroir",    type: "radius",  group: "style",    default: "3xl" },
      { name: "background",         label: "Fond",            type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",       label: "Rayon bordure",   type: "radius",  group: "style",    default: "none" },
      { name: "defaultOpen",        label: "Ouvert par défaut", type: "boolean", group: "behavior", default: false },
      { name: "handleColor",        label: "Couleur handle",  type: "color",   group: "style",    themeDefault: "primary" },
      { name: "backdropOpacity",    label: "Opacité backdrop", type: "ratio",  group: "style",    default: 0.4, min: 0, max: 1 },
      { name: "contentScaleWhenOpen", label: "Scale contenu ouvert", type: "ratio", group: "behavior", default: 0.95, min: 0.5, max: 1 },
      { name: "handleBarColor",     label: "Couleur barre handle", type: "color",  group: "style",    themeDefault: "border" },
      { name: "handleButtonSize",   label: "Taille bouton handle", type: "number", group: "layout",   default: 56 },
    ],
  },

  {
    id: "TopDrawerLayout",
    label: "Tiroir haut",
    description: "Tiroir supérieur animé avec geste de swipe.",
    category: "navigation",
    themeMapping: { root: "background", drawer: "background", border: "border", muted: "muted" },
    constants: {
      springConfig: { damping: 25, stiffness: 200, mass: 0.5, overshootClamping: true },
    },
    slots: [
      { name: "content",       label: "Contenu principal",  required: true,  kind: "named" },
      { name: "drawerContent", label: "Contenu du tiroir",  required: true,  kind: "named" },
    ],
    responsive: false,
    animated: true,
    dependencies: ["react-native-reanimated", "react-native-gesture-handler", "expo-haptics"],
    tags: ["drawer", "top-sheet", "swipe", "notification"],
    props: [
      { name: "drawerHeight",       label: "Hauteur tiroir",    type: "number",  group: "layout",   default: 600 },
      { name: "maxWidth",           label: "Largeur max",       type: "number",  group: "layout" },
      { name: "scrollable",         label: "Scrollable",        type: "boolean", group: "behavior", default: true },
      { name: "drawerBackground",   label: "Fond tiroir",       type: "color",   group: "style",    themeDefault: "background" },
      { name: "drawerBorderRadius", label: "Rayon tiroir",      type: "radius",  group: "style",    default: "3xl" },
      { name: "background",         label: "Fond",              type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",       label: "Rayon bordure",     type: "radius",  group: "style",    default: "none" },
      { name: "defaultOpen",        label: "Ouvert par défaut", type: "boolean", group: "behavior", default: false },
      { name: "handleColor",        label: "Couleur handle",    type: "color",   group: "style",    themeDefault: "border" },
      { name: "backdropOpacity",    label: "Opacité backdrop",  type: "ratio",   group: "style",    default: 0.4, min: 0, max: 1 },
      { name: "contentScaleWhenOpen", label: "Scale contenu ouvert", type: "ratio", group: "behavior", default: 0.95, min: 0.5, max: 1 },
      { name: "closeButtonBackground", label: "Fond bouton fermer",    type: "color",  group: "style",  themeDefault: "muted" },
      { name: "closeButtonSize",        label: "Taille bouton fermer",  type: "number", group: "layout", default: 36 },
      { name: "closeButtonBorderColor", label: "Bordure bouton fermer", type: "color",  group: "style",  themeDefault: "border" },
      { name: "closeButtonTextColor",   label: "Texte bouton fermer",   type: "color",  group: "style",  themeDefault: "mutedForeground" },
    ],
  },

  {
    id: "LeftDrawerLayout",
    label: "Tiroir gauche",
    description: "Tiroir latéral gauche animé avec geste de swipe.",
    category: "navigation",
    themeMapping: { root: "background", drawer: "background", accent: "primary", border: "border" },
    constants: {
      springConfig: { damping: 25, stiffness: 200, mass: 0.5, overshootClamping: true },
    },
    slots: [
      { name: "content",       label: "Contenu principal",  required: true,  kind: "named" },
      { name: "drawerContent", label: "Contenu du tiroir",  required: true,  kind: "named" },
    ],
    responsive: false,
    animated: true,
    dependencies: ["react-native-reanimated", "react-native-gesture-handler", "expo-haptics"],
    tags: ["drawer", "side-menu", "swipe", "navigation"],
    props: [
      { name: "drawerWidth",        label: "Largeur tiroir",    type: "number",  group: "layout",   default: 280 },
      { name: "maxWidth",           label: "Largeur max",       type: "number",  group: "layout" },
      { name: "scrollable",         label: "Scrollable",        type: "boolean", group: "behavior", default: true },
      { name: "drawerBackground",   label: "Fond tiroir",       type: "color",   group: "style",    themeDefault: "background" },
      { name: "drawerBorderRadius", label: "Rayon tiroir",      type: "radius",  group: "style",    default: "none" },
      { name: "background",         label: "Fond",              type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",       label: "Rayon bordure",     type: "radius",  group: "style",    default: "none" },
      { name: "defaultOpen",        label: "Ouvert par défaut", type: "boolean", group: "behavior", default: false },
      { name: "handleColor",        label: "Couleur handle",    type: "color",   group: "style",    themeDefault: "primary" },
      { name: "backdropOpacity",    label: "Opacité backdrop",  type: "ratio",   group: "style",    default: 0.4, min: 0, max: 1 },
      { name: "contentScaleWhenOpen", label: "Scale contenu ouvert", type: "ratio", group: "behavior", default: 0.98, min: 0.5, max: 1 },
      { name: "handleBarColor",     label: "Couleur barre handle", type: "color",  group: "style",    themeDefault: "border" },
      { name: "handleBarWidth",     label: "Largeur zone geste",   type: "number", group: "layout",   default: 40 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CARD
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "DeckLayout",
    label: "Deck",
    description: "Stack de cartes swipeable avec effet de profondeur.",
    category: "card",
    constants: {
      swipeThreshold: 60,
      exitDistance: 450,
      springConfig: { damping: 20, stiffness: 200, mass: 0.5 },
    },
    slots: [{ name: "items", label: "Cartes", required: true, kind: "items" }],
    responsive: false,
    animated: true,
    previewItemCount: 4,
    dependencies: ["react-native-reanimated", "react-native-gesture-handler", "expo-haptics"],
    tags: ["deck", "cards", "swipe", "tinder", "stack"],
    props: [
      { name: "peekOffset",       label: "Décalage peek",    type: "number",  group: "layout",   default: 12 },
      { name: "peekScale",        label: "Échelle peek",     type: "ratio",   group: "layout",   default: 0.05, min: 0, max: 0.2 },
      { name: "cycle",            label: "Boucle",           type: "boolean", group: "behavior", default: false },
      { name: "cardShadow",       label: "Ombre cartes",     type: "boolean", group: "style",    default: true },
      { name: "cardBackground",   label: "Fond carte",       type: "color",   group: "style",    themeDefault: "card" },
      { name: "cardBorderRadius", label: "Rayon carte",      type: "radius",  group: "style",    default: 24 },
      { name: "containerWidth",   label: "Largeur container", type: "string", group: "layout",   default: "90%" },
      { name: "containerHeight",  label: "Hauteur container", type: "string", group: "layout",   default: "75%" },
      { name: "peekCount",        label: "Cartes en arrière", type: "number", group: "layout",   default: 2 },
      { name: "peekRotation",     label: "Rotation peek",     type: "number",  group: "layout",   default: 0 },
      { name: "direction",        label: "Direction",         type: "enum",    group: "behavior", default: "horizontal", options: ["horizontal", "vertical"] },
      { name: "background",       label: "Fond",              type: "color",   group: "style",    themeDefault: "background" },
    ],
  },

  {
    id: "FlipLayout",
    label: "Flip",
    description: "Carousel avec flip recto/verso et swipe horizontal.",
    category: "card",
    themeMapping: { root: "background", surface: "card" },
    constants: {
      flipThreshold: 22,
      scaleFactor: 0.92,
      flipScaleFactor: 0.90,
      springNoBounce: { damping: 30, stiffness: 240, mass: 0.6 },
      springSnap: { damping: 35, stiffness: 300, mass: 0.5 },
      exitLeft: -700,
      exitRight: 700,
    },
    slots: [
      { name: "items",       label: "Faces recto", required: true,  kind: "items" },
      { name: "backContent", label: "Faces verso", required: false, kind: "named-array" },
    ],
    responsive: false,
    animated: true,
    previewItemCount: 3,
    dependencies: ["react-native-reanimated", "react-native-gesture-handler"],
    tags: ["flip", "card", "recto-verso", "flashcard"],
    props: [
      { name: "maxWidth",          label: "Largeur max",       type: "number",  group: "layout" },
      { name: "background",        label: "Fond",              type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",      label: "Rayon bordure",     type: "radius",  group: "style",    default: "none" },
      { name: "cardBackground",    label: "Fond carte",        type: "color",   group: "style",    themeDefault: "card" },
      { name: "flipPerspective",   label: "Perspective flip",  type: "number",  group: "layout",   default: 1200 },
      { name: "swipeThreshold",    label: "Seuil swipe",       type: "number",  group: "behavior", default: 40 },
      { name: "padding",           label: "Padding",           type: "padding", group: "layout" },
      { name: "cardBorderRadius",  label: "Rayon carte",       type: "radius",  group: "style",    default: 20 },
      { name: "cardAspectRatio",   label: "Ratio carte (web)", type: "number",  group: "layout",   default: 0.5625, description: "Ratio largeur/hauteur sur web — omis = adaptatif" },
      { name: "cardMaxHeight",     label: "Hauteur max carte", type: "number",  group: "layout",   description: "Hauteur max en px — omis = pas de limite" },
      { name: "dezoomDuration",    label: "Durée dézoom",      type: "number",  group: "behavior", default: 120 },
      { name: "flipDuration",      label: "Durée flip",        type: "number",  group: "behavior", default: 320 },
      { name: "slideOutDuration",  label: "Durée slide out",   type: "number",  group: "behavior", default: 140 },
    ],
  },

  {
    id: "SwiperLayout",
    label: "Swiper",
    description: "Carousel swipeable multi-directionnel avec préchargement.",
    category: "card",
    themeMapping: { root: "background", surface: "card" },
    constants: {
      scaleFactor: 0.85,
    },
    slots: [{ name: "items", label: "Slides", required: true, kind: "items" }],
    responsive: false,
    animated: true,
    previewItemCount: 4,
    dependencies: ["react-native-reanimated", "react-native-gesture-handler"],
    tags: ["swiper", "carousel", "slides", "stories"],
    props: [
      { name: "enableSwipeUp",   label: "Swipe haut",       type: "boolean", group: "behavior", default: false },
      { name: "enableSwipeDown",  label: "Swipe bas",        type: "boolean", group: "behavior", default: false },
      { name: "maxWidth",         label: "Largeur max",      type: "number",  group: "layout" },
      { name: "background",       label: "Fond",             type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",     label: "Rayon bordure",    type: "radius",  group: "style",    default: "none" },
      { name: "cardBackground",   label: "Fond carte",       type: "color",   group: "style",    themeDefault: "card" },
      { name: "cardBorderRadius", label: "Rayon carte",      type: "radius",  group: "style",    default: "none" },
      { name: "showCardCount",    label: "Compteur cartes",  type: "boolean", group: "behavior", default: false },
      { name: "preloadRange",     label: "Préchargement",    type: "number",  group: "behavior", default: 2 },
      { name: "swipeThreshold",   label: "Seuil swipe",      type: "number",  group: "behavior", default: 40 },
      { name: "padding",          label: "Padding",          type: "padding", group: "layout" },
      { name: "springDamping",    label: "Amortissement spring", type: "number", group: "behavior", default: 12 },
      { name: "springStiffness",  label: "Raideur spring",       type: "number", group: "behavior", default: 160 },
      { name: "cardCountBackground", label: "Fond compteur",  type: "color",  group: "style",    default: "rgba(0,0,0,0.6)" },
      { name: "cardCountTextColor",  label: "Texte compteur", type: "color",  group: "style",    default: "#fff" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SCROLL
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "ScrollLayout",
    label: "Scroll",
    description: "Structure scrollable avec header/footer sticky ou inline.",
    category: "scroll",
    themeMapping: { root: "background", surface: "card" },
    slots: [
      { name: "content", label: "Contenu", required: true,  kind: "named" },
      { name: "header",  label: "Header",  required: false, kind: "named" },
      { name: "footer",  label: "Footer",  required: false, kind: "named" },
    ],
    responsive: true,
    animated: false,
    tags: ["scroll", "sticky", "header", "footer", "safe-area"],
    props: [
      { name: "spacing",             label: "Espacement",         type: "spacing",  group: "layout",   default: 4 },
      { name: "useSafeAreaInsets",    label: "Safe area",          type: "boolean",  group: "behavior", default: true },
      { name: "headerHeight",        label: "Hauteur header",     type: "number",   group: "layout",   default: 80 },
      { name: "footerHeight",        label: "Hauteur footer",     type: "number",   group: "layout",   default: 60 },
      { name: "scrollDirection",     label: "Direction scroll",   type: "enum",     group: "behavior", default: "vertical", options: ["vertical", "horizontal", "both"] },
      { name: "showScrollIndicator", label: "Indicateur scroll",  type: "boolean",  group: "behavior", default: false },
      { name: "enableBounces",       label: "Rebond",             type: "boolean",  group: "behavior", default: true },
      { name: "stickyHeader",        label: "Header sticky",      type: "boolean",  group: "behavior", default: false },
      { name: "stickyFooter",        label: "Footer sticky",      type: "boolean",  group: "behavior", default: false },
      { name: "background",          label: "Fond",               type: "color",    group: "style",    themeDefault: "background" },
      { name: "borderRadius",        label: "Rayon bordure",      type: "radius",   group: "style",    default: "none" },
      { name: "headerBackground",    label: "Fond header",        type: "color",    group: "style",    themeDefault: "card" },
      { name: "footerBackground",    label: "Fond footer",        type: "color",    group: "style",    themeDefault: "card" },
      { name: "contentBackground",   label: "Fond contenu",       type: "color",    group: "style" },
      { name: "headerPadding",       label: "Padding header",     type: "spacing",  group: "layout",   default: 4 },
      { name: "footerPadding",       label: "Padding footer",     type: "spacing",  group: "layout",   default: 4 },
      { name: "mobileHeaderHeight",  label: "Hauteur header mobile", type: "number", group: "layout",  default: 60 },
      { name: "mobileFooterHeight",  label: "Hauteur footer mobile", type: "number", group: "layout",  default: 50 },
    ],
  },

  {
    id: "HeaderContentLayout",
    label: "Header collapsible",
    description: "Header qui se réduit au scroll avec contenu principal.",
    category: "scroll",
    themeMapping: { root: "background", header: "card", content: "card" },
    slots: [
      { name: "header",  label: "Header",  required: true, kind: "named" },
      { name: "content", label: "Contenu", required: true, kind: "named" },
    ],
    responsive: false,
    animated: true,
    dependencies: ["react-native-reanimated"],
    tags: ["header", "collapsible", "scroll", "parallax"],
    props: [
      { name: "headerHeight",          label: "Hauteur header",          type: "number",  group: "layout",   default: 150 },
      { name: "headerCollapsedHeight", label: "Hauteur header réduit",   type: "number",  group: "layout",   default: 60 },
      { name: "spacing",               label: "Espacement",              type: "spacing", group: "layout",   default: 0 },
      { name: "maxWidth",              label: "Largeur max",             type: "number",  group: "layout" },
      { name: "headerBackground",      label: "Fond header",             type: "color",   group: "style",    themeDefault: "card" },
      { name: "headerBorderRadius",    label: "Rayon header",            type: "radius",  group: "style",    default: "none" },
      { name: "contentBackground",     label: "Fond contenu",            type: "color",   group: "style",    themeDefault: "card" },
      { name: "contentBorderRadius",   label: "Rayon contenu",           type: "radius",  group: "style",    default: "none" },
      { name: "background",            label: "Fond",                    type: "color",   group: "style",    themeDefault: "background" },
      { name: "borderRadius",          label: "Rayon bordure",           type: "radius",  group: "style",    default: "none" },
      { name: "padding",               label: "Padding contenu",         type: "spacing", group: "layout",   default: 5 },
      { name: "headerPadding",         label: "Padding header",          type: "spacing", group: "layout",   default: 5 },
      { name: "scrollEventThrottle",   label: "Throttle scroll event",   type: "number",  group: "behavior", default: 16 },
    ],
  },

  {
    id: "ParallaxLayout",
    label: "Parallax",
    description: "Rangées horizontales scrollables avec synchronisation parallaxe. Les items sont distribués automatiquement en rangées selon itemsPerRow.",
    category: "scroll",
    slots: [{ name: "items", label: "Items", required: true, kind: "items" }],
    responsive: false,
    animated: true,
    previewItemCount: 9,
    dependencies: ["react-native-reanimated"],
    tags: ["parallax", "horizontal", "sync", "showcase"],
    props: [
      // Layout
      { name: "rowCount",           label: "Nombre de rangées",   type: "number",  group: "layout",   default: 3 },
      { name: "itemWidth",          label: "Largeur item",        type: "number",  group: "layout",   default: 200 },
      { name: "spacing",            label: "Espacement vertical", type: "spacing", group: "layout",   default: 4 },
      { name: "itemSpacing",        label: "Espacement items",    type: "number",  group: "layout",   default: 12 },
      // Style
      { name: "background",         label: "Fond",                type: "color",   group: "style",    themeDefault: "background" },
      { name: "rowBackground",      label: "Fond rangée",         type: "color",   group: "style" },
      { name: "itemBackground",     label: "Fond item",           type: "color",   group: "style",    themeDefault: "card" },
      { name: "itemBorderRadius",   label: "Rayon item",          type: "radius",  group: "style",    default: "none" },
      { name: "rowBorderRadius",    label: "Rayon rangée",        type: "radius",  group: "style",    default: "none" },
      // Behavior
      { name: "alternateDirection", label: "Direction alternée",  type: "boolean", group: "behavior", default: true },
      { name: "bounces",            label: "Rebond scroll",       type: "boolean", group: "behavior", default: false },
      { name: "showScrollIndicator", label: "Indicateur scroll",  type: "boolean", group: "behavior", default: false },
      { name: "scrollEventThrottle", label: "Throttle scroll",    type: "number",  group: "behavior", default: 16 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPECIAL
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "TutoLayout",
    label: "Tutoriel",
    description: "Overlay de tutoriel avec zones highlight et gestes.",
    category: "special",
    themeMapping: { root: "background", accent: "primary", text: "foreground" },
    constants: {
      swipeThreshold: 40,
    },
    slots: [{ name: "children", label: "Contenu à annoter", required: true, kind: "children" }],
    responsive: false,
    animated: true,
    dependencies: ["react-native-reanimated"],
    tags: ["tutorial", "onboarding", "highlight", "walkthrough"],
    props: [
      { name: "overlayOpacity", label: "Opacité overlay",  type: "ratio",   group: "style",    default: 0.78, min: 0, max: 1 },
      { name: "overlayColor",   label: "Couleur overlay",  type: "color",   group: "style" },
      { name: "showSkip",       label: "Bouton ignorer",   type: "boolean", group: "behavior", default: true },
      { name: "nextLabel",      label: "Label suivant",    type: "string",  group: "content",  default: "Suivant" },
      { name: "finishLabel",    label: "Label terminer",   type: "string",  group: "content",  default: "Terminer" },
      { name: "accentColor",    label: "Couleur accent",   type: "color",   group: "style",    themeDefault: "primary" },
      { name: "textBackground", label: "Fond texte",       type: "color",   group: "style",    themeDefault: "background" },
      { name: "textColor",      label: "Couleur texte",    type: "color",   group: "style",    themeDefault: "foreground" },
      { name: "mutedTextColor", label: "Texte secondaire", type: "color",   group: "style",    themeDefault: "mutedForeground" },
      { name: "steps",          label: "Étapes",           type: "json",    group: "content",  default: [] },
    ],
  },

  {
    id: "SketchLayout",
    label: "Sketch (placeholder)",
    description: "Placeholder pour un canvas de dessin.",
    category: "special",
    slots: [],
    responsive: false,
    animated: false,
    tags: ["sketch", "draw", "canvas", "placeholder"],
    props: [
      { name: "background", label: "Fond", type: "color", group: "style", themeDefault: "background" },
    ],
  },

  {
    id: "Swipe2ScreenLayout",
    label: "Swipe to Screen",
    description: "Layout de présentation avec swipe vers un écran projeté et QR code.",
    category: "special",
    slots: [{ name: "items", label: "Slides", required: true, kind: "items" }],
    responsive: false,
    animated: true,
    previewItemCount: 3,
    dependencies: ["react-native-gesture-handler", "expo-camera", "expo-haptics"],
    tags: ["swipe", "projection", "qr", "slides"],
    props: [
      { name: "containerBackground", label: "Fond container",  type: "color",  group: "style",    default: "#000" },
      { name: "screenBackground",    label: "Fond écran",      type: "color",  group: "style",    default: "#fff" },
      { name: "swipeThreshold",      label: "Seuil swipe",     type: "number", group: "behavior", default: 100 },
      { name: "projectedScale",      label: "Scale projeté",   type: "ratio",  group: "behavior", default: 0.8, min: 0.5, max: 1 },
      { name: "animationDuration",   label: "Durée animation", type: "number", group: "behavior", default: 300 },
      { name: "slides",              label: "Slides",          type: "json",   group: "content",  default: [] },
    ],
  },

  {
    id: "SystemLayout",
    label: "System UI",
    description: "Wrapper système gérant StatusBar, SafeAreaView et NavigationBar.",
    category: "special",
    slots: [{ name: "children", label: "Contenu", required: true, kind: "children" }],
    responsive: false,
    animated: false,
    dependencies: ["expo-status-bar", "react-native-safe-area-context"],
    tags: ["system", "statusbar", "navigation-bar", "safe-area"],
    props: [
      { name: "rootBackgroundColor",       label: "Couleur fond racine",    type: "color", group: "style",    default: "#0c3ddbff" },
      { name: "statusBarContentStyle",     label: "Style barre statut",     type: "enum",  group: "behavior", default: "auto", options: ["light", "dark", "auto"] },
      { name: "edges",                     label: "Bords safe area",        type: "json",  group: "behavior", default: ["top", "bottom", "left", "right"] },
      { name: "navigationBarContentStyle", label: "Style barre navigation", type: "enum",  group: "behavior", options: ["light", "dark"] },
    ],
  },
];
