import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The whole documentation content is generated by
// design/tools/sources/docgen.py into docs/generated/ (never hand-edit it):
// a single autogenerated sidebar mirrors the generated section/article tree.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
