import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started & Guides',
      collapsed: false,
      items: [
        'guides/getting-started',
        'guides/theming-guide',
        'guides/architecture-guide',
        'guides/cli-guide',
      ],
    },
    {
      type: 'category',
      label: 'Design Tokens & Themes',
      collapsed: false,
      items: [
        'tokens/tokens',
        'theme/themes',
      ],
    },
    {
      type: 'category',
      label: 'UI Components',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Base Components',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'ui/components/base',
            },
          ],
        },
        {
          type: 'category',
          label: 'Layout Primitives',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'ui/components/layouts',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Web Client Package (@flipova/foundation/web)',
      collapsed: false,
      items: [
        'web/index',
        {
          type: 'category',
          label: 'Web Primitives',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'web/primitives',
            },
          ],
        },
        {
          type: 'category',
          label: 'Web Components',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'web/components',
            },
          ],
        },
        {
          type: 'category',
          label: 'Web Layouts',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'web/layouts',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Hooks & Utilities',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'React Hooks',
          items: [
            {
              type: 'autogenerated',
              dirName: 'ui/hooks',
            },
          ],
        },
        {
          type: 'category',
          label: 'Helper Utilities',
          items: [
            {
              type: 'autogenerated',
              dirName: 'ui/utils',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'System & Registry',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'config',
        },
        {
          type: 'autogenerated',
          dirName: 'registry',
        },
      ],
    },
  ],
};

export default sidebars;
