import type { BlockMeta } from "../../types";

export const existingBlocks: BlockMeta[] = [
  {
    id: "AuthFormBlock",
    label: "Auth Form",
    description: "Login/signup form with email, password, submit button, and optional social providers.",
    category: "auth",
    tags: ["auth", "login", "signup", "form", "email", "password"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary" },
    components: ["TextInput", "Button"],
    slots: [
      { name: "header", label: "Header (logo/title)", required: false, kind: "named" },
      { name: "footer", label: "Footer (links)",       required: false, kind: "named" },
      { name: "social", label: "Social providers",     required: false, kind: "named-array" },
    ],
    props: [
      { name: "mode",          label: "Mode",            type: "enum",    group: "behavior", default: "login", options: ["login", "signup", "forgot"] },
      { name: "showRemember",  label: "Remember me",     type: "boolean", group: "behavior", default: true },
      { name: "showForgot",    label: "Forgot password", type: "boolean", group: "behavior", default: true },
      { name: "spacing",       label: "Spacing",         type: "spacing", group: "layout",   default: 4 },
      { name: "background",    label: "Background",      type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius",  label: "Border radius",   type: "radius",  group: "style",    default: "xl" },
      { name: "padding",       label: "Padding",         type: "spacing", group: "layout",   default: 5 },
      { name: "buttonVariant", label: "Button variant",  type: "enum",    group: "style",    default: "primary", options: ["primary", "secondary", "outline"] },
      { name: "inputVariant",  label: "Input variant",   type: "enum",    group: "style",    default: "outlined", options: ["outlined", "filled", "underline"] },
      { name: "submitLabel",   label: "Submit label",    type: "string",  group: "content",  default: "Sign In" },
      { name: "forgotLabel",   label: "Forgot label",    type: "string",  group: "content",  default: "Forgot password?" },
    ],
  },
  {
    id: "AvatarBlock",
    label: "Avatar Block",
    description: "Avatar with name, subtitle, and optional action.",
    category: "profile",
    tags: ["avatar", "user", "profile", "name"],
    themeMapping: { bg: "card", text: "foreground", subtitle: "mutedForeground" },
    components: ["Avatar"],
    slots: [{ name: "action", label: "Action button", required: false, kind: "named" }],
    props: [
      { name: "name",         label: "Name",          type: "string",  group: "content" },
      { name: "subtitle",     label: "Subtitle",      type: "string",  group: "content" },
      { name: "source",       label: "Image URL",     type: "string",  group: "content" },
      { name: "initials",     label: "Initials",      type: "string",  group: "content" },
      { name: "size",         label: "Avatar size",   type: "enum",    group: "style",    default: "md", options: ["sm", "md", "lg", "xl"] },
      { name: "direction",    label: "Direction",     type: "enum",    group: "layout",   default: "row", options: ["row", "column"] },
      { name: "spacing",      label: "Spacing",       type: "spacing", group: "layout",   default: 3 },
      { name: "showSubtitle", label: "Show subtitle", type: "boolean", group: "behavior", default: true },
    ],
  },
  {
    id: "HeaderBlock",
    label: "Header Bar",
    description: "Top navigation bar with title, back button, and right actions.",
    category: "navigation",
    tags: ["header", "navbar", "topbar", "navigation", "back"],
    themeMapping: { bg: "card", text: "foreground", border: "border" },
    components: ["IconButton"],
    slots: [
      { name: "left",  label: "Left actions",  required: false, kind: "named" },
      { name: "title", label: "Title area",    required: true,  kind: "named" },
      { name: "right", label: "Right actions", required: false, kind: "named-array" },
    ],
    props: [
      { name: "height",       label: "Height",        type: "number",  group: "layout",   default: 56 },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderBottom", label: "Bottom border", type: "boolean", group: "style",    default: true },
      { name: "padding",      label: "Padding",       type: "spacing", group: "layout",   default: 4 },
      { name: "transparent",  label: "Transparent",   type: "boolean", group: "style",    default: false },
    ],
  },
  {
    id: "SearchBarBlock",
    label: "Search Bar",
    description: "Search input with icon and optional filter button.",
    category: "navigation",
    tags: ["search", "input", "filter", "bar"],
    themeMapping: { bg: "muted", text: "foreground", placeholder: "mutedForeground" },
    components: ["TextInput", "IconButton"],
    slots: [{ name: "filters", label: "Filter actions", required: false, kind: "named-array" }],
    props: [
      { name: "placeholder",  label: "Placeholder",   type: "string",  group: "content",  default: "Search..." },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "muted" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "full" },
      { name: "showFilter",   label: "Show filter",   type: "boolean", group: "behavior", default: false },
      { name: "inputVariant", label: "Input variant", type: "enum",    group: "style",    default: "filled", options: ["outlined", "filled"] },
    ],
  },
  {
    id: "StatCardBlock",
    label: "Stat Card",
    description: "Metric card with value, label, trend indicator, and optional icon.",
    category: "data",
    tags: ["stat", "metric", "card", "kpi", "dashboard"],
    themeMapping: { bg: "card", text: "foreground", accent: "primary", muted: "mutedForeground" },
    components: ["Badge"],
    slots: [{ name: "icon", label: "Icon", required: false, kind: "named" }],
    props: [
      { name: "value",        label: "Value",         type: "string",  group: "content" },
      { name: "label",        label: "Label",         type: "string",  group: "content" },
      { name: "trend",        label: "Trend",         type: "string",  group: "content" },
      { name: "trendUp",      label: "Trend up",      type: "boolean", group: "content",  default: true },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "xl" },
      { name: "padding",      label: "Padding",       type: "spacing", group: "layout",   default: 4 },
      { name: "showTrend",    label: "Show trend",    type: "boolean", group: "behavior", default: true },
      { name: "shadow",       label: "Shadow",        type: "shadow",  group: "style",    default: "sm" },
    ],
  },
  {
    id: "EmptyStateBlock",
    label: "Empty State",
    description: "Placeholder for empty lists or screens with icon, title, description, and action.",
    category: "feedback",
    tags: ["empty", "placeholder", "no-data", "illustration"],
    themeMapping: { text: "mutedForeground", accent: "primary" },
    components: ["Button"],
    slots: [{ name: "illustration", label: "Illustration", required: false, kind: "named" }],
    props: [
      { name: "title",         label: "Title",          type: "string",  group: "content" },
      { name: "description",   label: "Description",    type: "string",  group: "content" },
      { name: "actionLabel",   label: "Action label",   type: "string",  group: "content",  default: "Get started" },
      { name: "spacing",       label: "Spacing",        type: "spacing", group: "layout",   default: 4 },
      { name: "showAction",    label: "Show action",    type: "boolean", group: "behavior", default: true },
      { name: "actionVariant", label: "Action variant", type: "enum",    group: "style",    default: "primary", options: ["primary", "outline", "ghost"] },
    ],
  },
  {
    id: "ListItemBlock",
    label: "List Item",
    description: "Standard list row with leading icon/avatar, title, subtitle, and trailing action.",
    category: "content",
    tags: ["list", "item", "row", "cell"],
    themeMapping: { bg: "card", text: "foreground", subtitle: "mutedForeground", border: "border" },
    components: ["Avatar", "IconButton"],
    slots: [
      { name: "leading",  label: "Leading element",  required: false, kind: "named" },
      { name: "trailing", label: "Trailing element",  required: false, kind: "named" },
    ],
    props: [
      { name: "title",       label: "Title",        type: "string",  group: "content" },
      { name: "subtitle",    label: "Subtitle",     type: "string",  group: "content" },
      { name: "height",      label: "Height",       type: "number",  group: "layout",   default: 56 },
      { name: "spacing",     label: "Spacing",      type: "spacing", group: "layout",   default: 3 },
      { name: "showDivider", label: "Show divider", type: "boolean", group: "style",    default: true },
      { name: "pressable",   label: "Pressable",    type: "boolean", group: "behavior", default: true },
      { name: "background",  label: "Background",   type: "color",   group: "style",    themeDefault: "card" },
      { name: "padding",     label: "Padding",      type: "spacing", group: "layout",   default: 4 },
    ],
  },
  {
    id: "FormBlock",
    label: "Form",
    description: "Form container with validation, submit handling, and field layout.",
    category: "form",
    tags: ["form", "validation", "submit", "fields"],
    themeMapping: { bg: "card", text: "foreground", error: "destructive" },
    components: ["TextInput", "Button", "Select", "Checkbox", "Switch"],
    slots: [
      { name: "children", label: "Form fields", required: true,  kind: "children" },
      { name: "header",   label: "Form header", required: false, kind: "named" },
      { name: "footer",   label: "Form footer", required: false, kind: "named" },
    ],
    props: [
      { name: "spacing",        label: "Spacing",          type: "spacing", group: "layout",   default: 4 },
      { name: "padding",        label: "Padding",          type: "spacing", group: "layout",   default: 4 },
      { name: "background",     label: "Background",       type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius",   label: "Border radius",    type: "radius",  group: "style",    default: "xl" },
      { name: "showReset",      label: "Show reset",       type: "boolean", group: "behavior", default: false },
      { name: "submitLabel",    label: "Submit label",     type: "string",  group: "content",  default: "Submit" },
      { name: "submitVariant",  label: "Submit variant",   type: "enum",    group: "style",    default: "primary", options: ["primary", "secondary", "outline"] },
      { name: "validateOnBlur", label: "Validate on blur", type: "boolean", group: "behavior", default: true },
      { name: "resetLabel",     label: "Reset label",      type: "string",  group: "content",  default: "Reset" },
    ],
  },
  {
    id: "CardBlock",
    label: "Card",
    description: "Content card with optional image, title, description, and actions.",
    category: "content",
    tags: ["card", "content", "media", "article"],
    themeMapping: { bg: "card", text: "foreground", subtitle: "mutedForeground" },
    components: ["Button", "Badge"],
    slots: [
      { name: "media",   label: "Media (image/video)", required: false, kind: "named" },
      { name: "actions", label: "Action buttons",      required: false, kind: "named-array" },
    ],
    props: [
      { name: "title",        label: "Title",         type: "string",  group: "content" },
      { name: "description",  label: "Description",   type: "string",  group: "content" },
      { name: "padding",      label: "Padding",       type: "spacing", group: "layout",   default: 4 },
      { name: "spacing",      label: "Spacing",       type: "spacing", group: "layout",   default: 3 },
      { name: "background",   label: "Background",    type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius", label: "Border radius", type: "radius",  group: "style",    default: "xl" },
      { name: "shadow",       label: "Shadow",        type: "shadow",  group: "style",    default: "sm" },
      { name: "pressable",    label: "Pressable",     type: "boolean", group: "behavior", default: false },
    ],
  },
  {
    id: "ModalBlock",
    label: "Modal",
    description: "Modal overlay with content, close button, and backdrop.",
    category: "overlay",
    tags: ["modal", "dialog", "popup", "overlay"],
    themeMapping: { bg: "card", text: "foreground", backdrop: "background" },
    components: ["IconButton"],
    slots: [
      { name: "children", label: "Content",        required: true,  kind: "children" },
      { name: "footer",   label: "Footer actions", required: false, kind: "named" },
    ],
    props: [
      { name: "padding",       label: "Padding",           type: "spacing", group: "layout",   default: 5 },
      { name: "background",    label: "Background",        type: "color",   group: "style",    themeDefault: "card" },
      { name: "borderRadius",  label: "Border radius",     type: "radius",  group: "style",    default: "2xl" },
      { name: "maxWidth",      label: "Max width",         type: "number",  group: "layout",   default: 500 },
      { name: "showClose",     label: "Show close",        type: "boolean", group: "behavior", default: true },
      { name: "backdropClose", label: "Close on backdrop", type: "boolean", group: "behavior", default: true },
    ],
  },
  {
    id: "ToastBlock",
    label: "Toast",
    description: "Notification toast with icon, message, and auto-dismiss.",
    category: "feedback",
    tags: ["toast", "notification", "snackbar", "alert"],
    themeMapping: { bg: "card", text: "foreground" },
    components: ["IconButton"],
    slots: [],
    props: [
      { name: "message",      label: "Message",        type: "string",  group: "content" },
      { name: "type",         label: "Type",           type: "enum",    group: "style",    default: "info", options: ["info", "success", "warning", "error"] },
      { name: "position",     label: "Position",       type: "enum",    group: "layout",   default: "top", options: ["top", "bottom"] },
      { name: "duration",     label: "Duration (ms)",  type: "number",  group: "behavior", default: 3000 },
      { name: "showIcon",     label: "Show icon",      type: "boolean", group: "behavior", default: true },
      { name: "dismissible",  label: "Dismissible",    type: "boolean", group: "behavior", default: true },
      { name: "borderRadius", label: "Border radius",  type: "radius",  group: "style",    default: "lg" },
    ],
  },
];
